### ISSUE TITLE
Android backend

### ISSUE THREAD

**Issue by neilogd** [jarikomppa/soloud#106]
SoLoud needs an Android port.  I'm going to do this soon (next month or so), so just putting an issue here for visibility, so if anyone else is doing it I don't waste any time, or if anyone else wants it - they can see it is on the cards.

My plan currently is:
- OpenSL ES backend.
- NEON optimised mixing.

Any thoughts, post here. Will post up any progress and fire over pull requests when I have something.

One thing I'm unsure of is how to go about getting the samples working (if I do at all) on Android, or rolling it into the build scripts. I've got my own build scripts forked from SoLoud's, and my own compiler setup hooked up to them. Any suggestions here? I think it's possible to use shared libraries (.so) on Android, so it could be possible to build them up, though I will just be statically linking SoLoud myself.

**Comment by jarikomppa** [comment]
Statically linking the examples is fine by me.

**Comment by jarikomppa** [comment]
note: issue #34 is openSL ES backend, adding this comment so we remember to close that too.

**Comment by neilogd** [comment]
WIP OpenSL ES backend work is located here for anyone interested:

https://github.com/neilogd/soloud/tree/features/opensles

**Comment by neilogd** [comment]
Currently in a semi-functional state, testing on a Nexus 7, and a Samsung S3 at the moment.

There are clicks when queuing up buffers right now, going to resolve this by using markers (seems to be how to do it...someone else may know better). Android appears to have it's own way to enqueue buffers in SLES, and I don't know another way to test on non-Android devices.

File IO is a little more problematic. I needed to pass in my own SoLoud::File object to go through my own file system to get this working. Can use AAssetManager & AAsset and implement an Android-specific DiskFile so that other people don't need to, or at least provide a reference one alongside SoLoud in a contrib folder. Thoughts here? Using regular fopen/fread/fclose isn't an option for files inside of APKs.

Once it's playing smoothly I'll profile the mixing and try get a NEON implementation done to keep the overhead low.

**Comment by jarikomppa** [comment]
I'll close this, the optimizations etc. are separate issues.

As for file I/O, as we talked on IRC, since android requires special code from the developer anyway, might as well leave the file I/O problems to the application.
