### ISSUE TITLE
with-sdl2static-only error in soloud-x86.lib

### ISSUE THREAD

**Issue by lilmike** [jarikomppa/soloud#108]
hi,
I downloaded the latest soloud version on the website. However, as I needed to compile it myself because I use the multithreaded vs library instead of multithreaded/dll, I found that when compiling the soloud static project, and then using the resulting library in my application, sdl_mutexv and sdl_mutexp are not found. I can't find references to those in the backend sdl2static, but perhaps I'm missing something. I tried with latest git, but unfortunately there's an  error about some audiof32 or something not being defined.
Thanks,
-Michael.

**Comment by jarikomppa** [comment]
The mutex functions have different names in SDL and SDL2, so that may explain the error. I assume that the operating system you're using is windows (based on the multithreaded options). Future versions should use non-sdl mutexes so that class of errors should go away (or at least change).

**Comment by jarikomppa** [comment]
This should no longer be an issue.
