### ISSUE TITLE
Compiling with just null driver not possible

### ISSUE THREAD

**Issue by petrihakkinen** [jarikomppa/soloud#109]
Currently it's not possible to compile soloud with just the null driver because WITH_NULL is missing from the check in soloud.cpp:

#if !defined(WITH_SDL2) && !defined(WITH_SDL) && !defined(WITH_PORTAUDIO) && !defined(WITH_OPENAL) && !defined(WITH_XAUDIO2) && !defined(WITH_WINMM) && !defined(WITH_WASAPI) && !defined(WITH_OSS) && !defined(WITH_SDL_STATIC) && !defined(WITH_SDL2_STATIC) && !defined(WITH_ALSA)

This would be useful for compiling on platforms that do not have any backends (yet).

**Comment by neilogd** [comment]
Yeah I had this when building for Android, so committed it to my fork but didn't do a pull request :)

**Comment by jarikomppa** [comment]
Thanks Neil.
