### ISSUE TITLE
Dynamic range compression

### ISSUE THREAD

**Issue by Dids** [jarikomppa/soloud#113]
Would it be possible to add dynamic range compression straight in to SoLoud, or simply as a filter?

I'm not 100% sure if that's the correct term for what I'm after, but I'm using SoLoud in a an upcoming game, and when two (or more) of the same audio clips play at roughly the same time, it can become loud.

This is where dynamic range compression would come in, and it would effectively adjust the volume, if the total volume would be considered as too loud.

**Comment by Dids** [comment]
I'm closing this, as I can't seem to reproduce this anymore with the latest release. :)

**Comment by jarikomppa** [comment]
This depends on what options you use to initialize SoLoud. The default
(basically) does dynamic range compression.

**Comment by Dids** [comment]
I noticed this! Or at least, I was under the impression it was doing this and I must've used SDL_mixer previously with no dynamic range compression, then must've just assumed that SoLoud doesn't either. Didn't even know it was a "thing", until after enough googling.

At any rate, SoLoud is awesome in every way. Got it currently setup with a 2D engine/game, doing positional audio. Works like a charm! :)

**Comment by jarikomppa** [comment]
For more detail, http://sol.gfxile.net/soloud/concepts.html and "clipping"
