### ISSUE TITLE
Not able to import - soloud on python 2.7.10 (32bit) on windows 

### ISSUE THREAD

**Issue by bangalorian** [jarikomppa/soloud#124]
Using windows 7.

Trying the use the soloud library.

 Put soloud.py, soloud_x86.dll, and msvcr100.dll into my python directory. The last one because of what i read on another issue.

When I type "import soloud", i get

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import soloud
  File "soloud.py", line 402, in <module>
    Soloud_mixSigned16 = soloud_dll.Soloud_mixSigned16
  File "C:\Python27\lib\ctypes__init__.py", line 378, in **getattr**
    func = self.**getitem**(name)
  File "C:\Python27\lib\ctypes__init__.py", line 383, in **getitem**
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'Soloud_mixSigned16' not found

Not sure how to fix this, and what I am doing wrong.

Thanks.

**Comment by jarikomppa** [comment]
Fixed. The codegen needed to be run, plus the glue generation code needed a couple of nudges.
