### ISSUE TITLE
Soloud::play can't play my sound, it is loaded successfully

### ISSUE THREAD

**Issue by brightening-eyes** [jarikomppa/soloud#129]
hello,
when i write s.play(menu_move); in my game loop (when user presses up or down arrow, it doesn't play anything
this is the code that i play the sound with it
Tolk_Speak successfully says my item using my screen reader, but s.play does not play my sound (the sound is valid
also when i use to change the volume of my sound with page up/page down keys, they don't work
this is the code of my menu's loop:
`while(SDL_PollEvent(&e))
{
if(e.type==SDL_KEYDOWN)
{
if(e.key.state==SDL_PRESSED&&e.key.keysym.sym==SDLK_DOWN)
{
if(pos<distance(menu_items.begin(), menu_items.begin()))
{
pos=menu_items.size()-1;
}
else if(pos>menu_items.size()-1)
{
pos=distance(menu_items.begin(), menu_items.begin());
}
pos++;
if(pos<distance(menu_items.begin(), menu_items.begin()))
{
pos=menu_items.size()-1;
}
else if(pos>menu_items.size()-1)
{
pos=distance(menu_items.begin(), menu_items.begin());
}
Tolk_Speak(menu_items[pos].c_str(), reader_interrupt);
s.play(menu_move);
}
if(e.key.state==SDL_PRESSED&&e.key.keysym.sym==SDLK_UP)
{
if(pos<distance(menu_items.begin(), menu_items.begin()))
{
pos=menu_items.size()-1;
}
else if(pos>menu_items.size()-1)
{
pos=distance(menu_items.begin(), menu_items.begin());
}
pos--;
if(pos<distance(menu_items.begin(), menu_items.begin()))
{
pos=menu_items.size()-1;
}
else if(pos>menu_items.size()-1)
{
pos=distance(menu_items.begin(), menu_items.begin());
}
Tolk_Speak(menu_items[pos].c_str(), reader_interrupt);
s.play(menu_move);
}
}
if(e.key.state==SDL_PRESSED&&e.key.keysym.sym==SDLK_RETURN)
{
int v=pos;
pos=0;
return v;
}`

and, this is the code that check's when pageup/down are pressed and change the volume respectively
`while(SDL_PollEvent(&e))
{
switch(e.type)
{
case SDL_QUIT:
quit=true;
exit(0);
break;
case SDL_KEYDOWN:
if(e.key.keysym.sym==SDLK_PAGEDOWN)
{
menumusic_volume-=0.1;
}
if(e.key.keysym.sym==SDLK_PAGEUP)
{
menumusic_volume+=0.1;
}
s.setVolume(menumusic_handle, menumusic_volume);
break;
}`
what the problem can be, just soloud doesn't work, everythink work's fine
i have to say when i execute the code outside the loop, it works (my menu music play's, but the volume doesn't change

**Comment by jarikomppa** [comment]
Sorry for the... rather long delay. Is this issue still relevant?

**Comment by brightening-eyes** [comment]
hi,
yup, it is exist yet
i don't know why is this happening, because it must be aible to play the sound (without the while loop it play's it!)
thanks in advance

**Comment by jarikomppa** [comment]
If you just comment out the volume setting calls, things work?

**Comment by brightening-eyes** [comment]
the volume does not change, and also it never play the sound in my while event loop
but my main music is played without any problem

**Comment by jarikomppa** [comment]
That is odd.
What does the init call look like?
If you break at the play calls, are they hit?
If you just call the play calls from your main, does the sample play then?
If you replace the menu_move sound with something else (like an sfxr
object), does that play?

**Comment by brightening-eyes** [comment]
hello,
init call is like this:
s.init();
play functions are called at main, and Tolk_Speak() which is for screen reader interaction works!
but, in the switch-case, soloud::play does not work which is for my event-detection loop
Tolk_Speak is called on that loop (Tolk_Speak works but soloud not)
I tried Sfxr now, and it doesn't work

**Comment by jarikomppa** [comment]
Where is 's' defined? In global scope?
Does playing menu_move sound work from main?
Does playing sfxr work from main?

**Comment by brightening-eyes** [comment]
s is a global variable
yup it works, menu_music which is a SoLoud::WavStream is called outside the while loop and it is working successfully
i didn't tried Sfxr in my main, but it seems that it works

**Comment by brightening-eyes** [comment]
hello again,
i tried sfxr in main (not in the game loop) and it worked, but in SDL's while loop (event detection), it doesn't work

**Comment by brightening-eyes** [comment]
hi,
i also tried WINMM backend and it doesn't work

**Comment by brightening-eyes** [comment]
hi,
i also tried WINMM backend and it doesn't work

**Comment by jarikomppa** [comment]
My guess is that you play around with the volume somewhere and that causes
the problem. Hard to debug further without seeing the whole source.

**Comment by brightening-eyes** [comment]
hi again,
i've commented that (the code that changes volume), but same result
also changed the backend to winmm and nothing
and, menumusic sample plays without any problem, but when i'm tring to play that in a while loop (at leest in my event detection), it doesn't work

**Comment by jarikomppa** [comment]
Sorry for being away for quite a long time, if this is still relevant (I doubt it), drop me a line.

**Comment by brightening-eyes** [comment]
hi,
the problem was from my code, the load() in the sample was called all the time in my game loop

**Comment by jarikomppa** [comment]
I'm surprised that didn't crash =).
Glad you found the problem.
