### ISSUE TITLE
PulseAudio backend

### ISSUE THREAD

**Issue by woollybah** [jarikomppa/soloud#132]
It would be nice to have a PulseAudio backend - for those who seem to like PulseAudio over the other backends on Linux.

**Comment by GWRon** [comment]
Any news regarding that backend?

**Comment by valid-ptr** [comment]
**NOTE**:

SDL2 backend can be used with the environment variable

`# export SDL_AUDIODRIVER="pulseaudio"`

See https://wiki.libsdl.org/FAQUsingSDL

**Comment by fungos** [comment]
It could also be done via mini_al: https://github.com/dr-soft/mini_al

**Comment by jarikomppa** [comment]
MiniAudio (formerly mini_al) has been integrated.
