### ISSUE TITLE
License of the audio files in the Demos

### ISSUE THREAD

**Issue by Flix01** [jarikomppa/soloud#133]
I'm trying to make an "amalgamation" file of SoLoud (basically all the source files in a single .h and .cpp file) and I was wandering if I can freely use some of the audio files of the Demos in my Demos too.

**Comment by jarikomppa** [comment]
As long as it's not for commercial use, there shouldn't be any limitations.
The stuff I've made can be totally freely used, but there's also .mod etc.
music which is not by me, so I can't vouch for those (apart for the
noncommercial use).

**Comment by Flix01** [comment]
Actually I'm just using <b>tetsno.ogg</b> (because it's small) for now. Is it yours ?

**Comment by jarikomppa** [comment]
Yes, feel free to use it.
