### ISSUE TITLE
Speech Valgrind-proof

### ISSUE THREAD

**Issue by Flix01** [jarikomppa/soloud#134]
Hi.
I've run Valgrind (a memory leak detector) and I've found that it's happier if we change:
```c++
	SpeechInstance::~SpeechInstance(){
               //delete mSample;	// old    
                delete[] mSample;  // new
	}
```

```c++
char * darray::getDataInPos(int aPosition) {
...
char *newdata = (char*)realloc(mData, newsize);
		if (!newdata)
		{
			free(mData);
			mData = NULL;
			mAllocated = mUsed = 0;
			return NULL;
		}
		else memset(newdata,0,newsize);	// new
...
}
```
Not sure that the latter is a real memory leak anyway...

**Comment by jarikomppa** [comment]
Hm, the last one will wipe anything that might have been in the old buffer
after it gets resized, so I'm not quite sure if it's okay.. =) I presume
your intention is to clear the newly allocated memory area to zero, which
is generally a good idea, which (if I haven't messed anything up here)
should be

*    memset(newdata + mAllocated, 0, newsize - mAllocated);*

**Comment by Flix01** [comment]
Yes, thank you for the correct fix: Valgrind is OK with the partial memset too (basically Valgrind detected that some uninitialized memory allocated there was triggering an if statement somewhere: so the behaviour was not deterministic or well defined).

P.S. I've found another memory leak when using pthreads.
```c++
		ThreadHandle createThread(threadFunction aThreadFunction, void *aParameter)
		{
			soloud_thread_data *d = new soloud_thread_data;
			d->mFunc = aThreadFunction;
			d->mParam = aParameter;

			ThreadHandleData *threadHandle = new ThreadHandleData;   // here: probably it's not released at the end
			pthread_create(&threadHandle->thread, NULL, threadfunc, (void*)d);
            return threadHandle;
		}
```

Tested with Linux + OpenAL. 
It does not happen with Linux + SDL2 (maybe it's not using pthreads).

**Comment by jarikomppa** [comment]
You're right, the thread handles are not collected and release() is not
explicitly called, so that's a potential leak. I don't think it's a real
one though.. Not 100% certain of that, though.
