### ISSUE TITLE
Fixed .wav parsing of "JUNK" chunk.

### ISSUE THREAD

**Issue by ocornut** [jarikomppa/soloud#137]
There's a chunk called "JUNK" which showed up in some of my wav and broke loading with Soloud.

Here's the documentation
https://www.daubnet.com/en/file-format-riff

And the fix
https://github.com/ocornut/soloud/commit/1048530276fde6b52ccb1bb173f807b573c5d051

Extra bonus, unrelated- disable warnings for Clang in klatt.cpp which uses an odd braces construct
https://github.com/ocornut/soloud/commit/87d74dad5b0f1d55d0e227e0d654264ceb68573f

**Comment by jarikomppa** [comment]
I'd rather fix the clang warnings than to ignore them..
