### ISSUE TITLE
Play PCM stream through C api

### ISSUE THREAD

**Issue by jimon** [jarikomppa/soloud#143]
I could be wrong, but looks like there is no way to play a PCM stream through C api. The piano sample creates an instance of AudioSourceInstance, but I don't see how it's possible to do through C api.

**Comment by jarikomppa** [comment]
Yes, extending soloud is only possible in c++. I've been thinking of adding some kind of generic streaming API, but it would basically require a callback and defining that in a environment-agnostic way is a bit difficult (if, for example, someone wants to stream custom audio from visual basic or something).

**Comment by Unit158** [comment]
Would it be unreasonable to implement PCM playback in a similar way to how the WAV AudioSource works, but without the header? (Specifying things such as bit depth, channels, etc. by constructor parameter?)

**Comment by jarikomppa** [comment]
This will be possible (with significant latency, but there you go) by using several Wav objects and the new Queue. The Wav objects now have raw wave loading functions, so one could just place couple of them to play in Queue, and check when Queue has finished playing one, re-cycle the object and place it back in Queue.

**Comment by jarikomppa** [comment]
demonstrated in 5791acde8d61fb60b32e6a35fdad93d7a1c15799
