### ISSUE TITLE
genie script generating wrong configuration for Win32 Visual Studio 2015

### ISSUE THREAD

**Issue by radgeRayden** [jarikomppa/soloud#144]
Using `genie --with-sdl2-only --platform=x32 --platform=x64 --with-libmodplug --with-tools vs2015` and  leaving all options in `genie.lua` untouched with the exception of SDL2 root folder and include I get the same `/lib/x64` SDL lib folder for both `Win32` and `x64` configurations.
Had to edit all non-lib projects to add the correct lib folder, which is `/lib/x86`. Naturally none of the examples will build otherwise.

I'm using the soloud_20160109 release from the website.

**Comment by radgeRayden** [comment]
Upon further inspection I noticed it also affects every output configuration, it always overwrites x64 libs (e.g. `soloud_static_x64.lib`) with x86 versions.

**Comment by jarikomppa** [comment]
Yeah, you can only use one platform at a time with genie, apparently.
