### ISSUE TITLE
Iphone no voice.

### ISSUE THREAD

**Issue by qcdong2016** [jarikomppa/soloud#146]
void init() {
    SoLoud::result c = soloud.init();
    const char\* s = soloud.getErrorString(c);
}
void play()
{
    SoLoud::Speech speech; // A sound source (speech, in this case)
    speech.setText("hello world.fuck you.");
    speech.setVolume(5);
    // Play the sound source (we could do this several times if we wanted)
    soloud.play(speech);
}

**Comment by jarikomppa** [comment]
I have no idea about the state of the iphone back end (or building for iphone for that matter), but I presume you've linked some back end?

**Comment by CaptainCN** [comment]
I tested coreaudio and openal. Aways no voice.

**Comment by jarikomppa** [comment]
*Shrug*. Pull requests are welcome.
