### ISSUE TITLE
compile error? (casting solves it)

### ISSUE THREAD

**Issue by francAmo** [jarikomppa/soloud#153]
casting error on windows, linux, ios platoforms.. (audiosource/wav/soloud_wavstream.cpp)
didn't want to change Soloud_Filehack typedef..

with regards..

P.S.
git diff to error free compile version.. 

@@ -68,7 +68,7 @@ namespace SoLoud
                        {
                                int e;

-                               mOgg = stb_vorbis_open_file((Soloud_Filehack *)mFile, 0, &e, 0);
+                               mOgg = stb_vorbis_open_file((FILE*)(Soloud_Filehack *)mFile, 0, &e, 0);

                                if (!mOgg)
                                {
@@ -386,7 +386,7 @@ namespace SoLoud
                fp->seek(0);
                int e;
                stb_vorbis *v;
-               v = stb_vorbis_open_file((Soloud_Filehack *)fp, 0, &e, 0);
+               v = stb_vorbis_open_file((FILE*)(Soloud_Filehack *)fp, 0, &e, 0);
                if (v == NULL)
                        return FILE_LOAD_FAILED;
                stb_vorbis_info info = stb_vorbis_get_info(v);

**Comment by francAmo** [comment]
delete all casting and use fp->getFilePtr() method

**Comment by jarikomppa** [comment]
Probably caused by using a non-modified stb_vorbis without the #include "soloud_filehack_on/off.h" lines.
