### ISSUE TITLE
Asus Xonar sound card problems

### ISSUE THREAD

**Issue by abadguy1** [jarikomppa/soloud#157]
Hello guys,
We're using SoLoud to play music in our game, however some people are having issues with Asus Xonar DS/D1/DGX sound cards.

https://youtu.be/CP1btsWcxhI

I don't know if it is a SoLoud problem or SDL2 one but I'll try to post here maybe someone can help.
SDL 2.0.4 static
SoLoud version 111

Edit: Updated both SDL2 and SoLoud to the leastest versions but some players are still encountering the same problem

**Comment by jarikomppa** [comment]
Try a different backend (winmm for example); the problem is more likely with the back end than with SoLoud, because SoLoud doesn't talk to hardware directly.
