### ISSUE TITLE
Sounds Randomly Silently Playing (w. SDL2 backend)

### ISSUE THREAD

**Issue by SnapperTT** [jarikomppa/soloud#163]
Hi,

I've been having issues with sounds not being audible at random. The sound's play() returns a valid handle, appear and contribute in the active voice counts and have non-zero volumes set, however cannot be heard. This effect is more likely to occur if there are already active sounds. I am nowhere near the voice limit when this occurs.

How do I debug this? Any ideas?
Cheers,
Twigz

**Comment by jarikomppa** [comment]
If only there was a code snippet to repro this..

**Comment by SnapperTT** [comment]
As you probably suspected this was an error on my part. Thanks anyway!
