### ISSUE TITLE
add Soloud::SetOriantation

### ISSUE THREAD

**Issue by brightening-eyes** [jarikomppa/soloud#165]
hello,
in order to inhance 3d in soloud, i think a function soloud::setOriantation is needed (changes the oriantation of a sound and/or listener)
maybe i dont know how to set the oriantation or it is not exist in soloud?

**Comment by jarikomppa** [comment]
Now, it's been a couple of years, so I may remember this wrong, but the idea is that the listener stays put and the audio sources move. The audio sources are all point sources.

**Comment by jarikomppa** [comment]
Turns out I remembered wrong! You can set the listener orienation using Soloud.set3dListenerPosition(), Soloud.set3dListenerAt() and Soloud.set3dListenerUp().
