### ISSUE TITLE
3d sound popping

### ISSUE THREAD

**Issue by Bananaft** [jarikomppa/soloud#175]
I'm having an issue similar to this one:
https://github.com/jarikomppa/soloud/issues/95
But I can't fix it with pause/unpause, or even by calling update3dVoices() right after play3d. It also does this full volume sound pop, every time when inaudible sound becomes  audible.

Here is the video:
https://youtu.be/YG9mBMdG7LQ 
Here I'm creating audio sources at the inaudible distance from camera. You can hear some of them pop. When they get closer the camera every single one of them pop.

month old soloud master branch. Windows 10 64, SDL2

**Comment by Bananaft** [comment]
Update: I hacked my way around by starting with zero volume, and then setting volume up in the next line:

`handle_ = soloud->play3d( *wav , p.x_ , p.y_ , p.z_ , 0.0f , 0.0f , 0.0f , 0.0f , false , 0U );
soloud->setVolume( handle_ , 1.0f );` 

I wonder if it adds a bit of delay. Doesn't looks like so.

**Comment by jarikomppa** [comment]
The audio will ramp from existing volume to the target volume in the first chunk. For some reason the initial "existing volume" isn't calculated right on the 3d sounds, need to look into it.

**Comment by stegei** [comment]
The issue is, that the mCurrentChannelVolume property of the voice is not correctly set in play3d/play3dClocked after the 3d data is calculated.
If fixed the issue by adding these few lines (copied from Soloud::play) after the call to updateVoiceVolume.

```
// Fix initial voice volume ramp up
int i;
for (i = 0; i < MAX_CHANNELS; i++)
{
	mVoice[v]->mCurrentChannelVolume[i] = mVoice[v]->mChannelVolume[i] * mVoice[v]->mOverallVolume;
}
```

**Comment by jarikomppa** [comment]
Thanks for digging into this.
