### ISSUE TITLE
Where is C# glue?

### ISSUE THREAD

**Issue by Krakean** [jarikomppa/soloud#176]
Hello @jarikomppa 
Looking at here: http://sol.gfxile.net/soloud/cs_api.html
https://i.imgur.com/UFvbUAt.png

then I go here and see:
https://i.imgur.com/HgrO9nG.png

Where is C# binding? :)

**Comment by jarikomppa** [comment]
Those files are autogenerated. You can either run the generation scripts
yourself, or download the latest release package which includes the
generated files.
