### ISSUE TITLE
creating synthisizers for SoLoud

### ISSUE THREAD

**Issue by brightening-eyes** [jarikomppa/soloud#179]
hi,
i think more samples specially synthisizers should be added to SoLoud
the one i know of is the padSynth algorithm available [here](http://zynaddsubfx.sourceforge.net/doc/PADsynth/PADsynth.htm) which is under public domain (the implementation is also available under the public domain
it can produce really great musical instrument loops

**Comment by jarikomppa** [comment]
Interesting. Thanks for the link.

**Comment by jarikomppa** [comment]
Added an implementation, as part of the piano example.
