### ISSUE TITLE
Reducing latency by caching

### ISSUE THREAD

**Issue by Dids** [jarikomppa/soloud#180]
I've been working with SoLoud (SDL2, macOS) for quite a while, and up until now it's been a fantastic experience all around, however I'm now starting to see severe audio latency on slower hardware (2015 MacBook with a fairly slow CPU).

Up until now, I've been caching audio clips (mapping filenames to audio clips), which I naively thought would work fine and effectively remove latency altogether, since I didn't have to recreate the audio clips, so there would only be initial latency when they were first played.

My question is: what could I potentially do to a) figure out what's causing the latency, and b) hopefully fix it or at the very least improve it?

I've thought about running SoLoud on it's own thread, but since multi-threading is a bit of a beast, I've been trying to avoid that if possible.

**Comment by jarikomppa** [comment]
Things you can try to reduce latency:
1. Try different backends, such as portaudio.
2. Try smaller buffer (set at SoLoud init call). Smaller buffer means less
latency but greater chance of buffer overruns.

**Comment by Dids** [comment]
Thank you very much. I reduced the buffer to a more comfortable size, which fixed the latency on it's own. I'll most likely need to keep tweaking it on a per project basis, but this is a great start. :)
