### ISSUE TITLE
#include <Windows.h> should be #include <windows.h>

### ISSUE THREAD

**Issue by avaskoog** [jarikomppa/soloud#182]
Hey there! Creating an issue for the thing I mentioned on Twitter.

In short, when cross-building for Windows on Linux using MinGW, the case sensitivity kicks in and the line `#include <Windows.h>` at the top of _soloud_thread.cpp_ causes the compile to fail, as the file is actually lowercase `windows.h`. That's it. The change does not affect the case insensitive build environment of actual Windows, so makes it work everywhere (confirmation: https://stackoverflow.com/questions/15466613/lowercase-windows-h-and-uppercase-windows-h-difference).

**Comment by jarikomppa** [comment]
Most of these should be done now: https://github.com/jarikomppa/soloud/commit/0e7caad7054c83945ac72a4de038037584fe4999
There's still at least one in 3rd party sources which I'm not going to touch right now.
