### ISSUE TITLE
DLL not functioning

### ISSUE THREAD

**Issue by JJLucena** [jarikomppa/soloud#184]
> Expected behavior:
The DLL should work and the dependency walker should return no error.

> Actual behavior:
The DLL is actually inaccessible and unusable and the dependency walker program returns some inconsistent calls to native windows DLLs that do not let the audio engine work properly.

> Steps to reproduce the problem:
Compile SoLoud with extra tools and try to use it or just scan it with dependency walker.

> SoLoud version, operating system, any other potentially useful information:
Last version, Windows 10, and here is an screenshot of the error:
<img width="1152" alt="screenshot" src="https://user-images.githubusercontent.com/37211429/46010331-886f8b00-c0c2-11e8-8388-d87da03a8ded.png">

**Comment by jarikomppa** [comment]
Is this the latest downloadable version or the latest from github?

Anyhow, it looks like you're mixing x64 and x32 DLLs.
