### ISSUE TITLE
Handle closed to early?

### ISSUE THREAD

**Issue by lamelizard** [jarikomppa/soloud#186]
Peace,
in `soloud_xaudio.cpp` during deinit it calls `data->xaudio2->StopEngine();` which calls `OnBufferEnd` which calls `SetEvent(mBufferEndEvent);`. This throws `0xC0000008: An invalid handle was specified`. Indeed, `mBufferEndEvent` was closed several lines before `data->xaudio2->StopEngine();`. Shouldn't it be closed later or am I the only one with this issue?
(Windows 10 x64 but compiling for x86 using MSVC)

**Comment by jarikomppa** [comment]
That is entirely possible. I didn't make the xaudio2 backend, so I don't
really know what's going on with it. If you can debug what's going on, pull
requests are welcome.
