### ISSUE TITLE
Support for surround speakers (4, 5.1 ,7.1, ...)

### ISSUE THREAD

**Issue by jarikomppa** [jarikomppa/soloud#19]
Architectural work: figure out what to actually do with the speakers
- Panning
  - "Stereo arc"
  - "Speaker fill"
- 3d audio
  - Also with stereo speakers..

**Comment by jarikomppa** [comment]
Support added, more or less - haven't tested at all, likely to have plenty of issues.

**Comment by a-teammate** [comment]
will this be part of the next release? And is there an ESTA for the next release?

**Comment by RobotCaleb** [comment]
^^

**Comment by JSandusky** [comment]
Don't forget direct play to the LFO/sub for grumbles.

**Comment by jarikomppa** [comment]
This is pretty much done now.
