### ISSUE TITLE
generate python 3 instead of python 2 in the glue scripts

### ISSUE THREAD

**Issue by brightening-eyes** [jarikomppa/soloud#202]
hi,
> Expected behavior:
SoLoud's script generation and the python's generated script is for python 2, but python 2 will be descontinued in 2020

> Actual behavior:
python 3 should be used for it instead

> Steps to reproduce the problem:
call to print should be in parentheses, and instead of doing ctypes.CDLL("soloud_x86"), it should be ctypes.cdll.soloud where soloud can be an x86 or an x64 dll

> SoLoud version, operating system, backend used, any other potentially useful information:
latest SoLoud version, even the latest source code

i think, maybe we can write a swig wrapper for it, since we can generate plugins for other languages as well.
or, boost.python for python is a good alternative, since python can be used to write filters, audio sources, or audio colliders (overriding virtual functions)

**Comment by jarikomppa** [comment]
Migrated to py3.
