### ISSUE TITLE
Positional audio randomly flipped/reversed/back-to-front

### ISSUE THREAD

**Issue by JacksonAllan** [jarikomppa/soloud#209]
Edit: Not a SoLoud problem.

**Comment by JacksonAllan** [comment]
Update:

I've done some more experimenting to try to pinpoint where the issue is, including printing details every time a sound is played. Here is an example of the info SoLoud reports for the volume of channels 0 (left) and 1 (right) (extracted through mVoice[ ... ]->mChannelVolume[ ... ] and the positions of those speakers (extracted via getSpeakerPosition( ... )) when as sound is played to the player's left:

When the sound is playing correctly (mainly out of the left speaker):
Vol: L 0.679 R 0.087; Speaker pos xyz: L 2.000 0.000 1.000 R -2.000 0.000 1.000

When the sound system is suffering from the random flipping problem (i.e. the sound is incorrectly playing mainly out of the right speaker) :
Vol: L 0.633 R 0.074; Speaker pos xyz: L 2.000 0.000 1.000 R -2.000 0.000 1.000

As you can see, the values are much the same. In both instances, the speaker positions are exactly the same, and the volume values indicated that SoLoud _thinks_ it is playing the sound from the left. In reality, in the second case, the sound was coming from the other speaker.

At this point, I'm at a bit of a loss. I'm not sure there's anything I can do besides ditching SoLoud for another library, which I'd really rather not do.

**Comment by jarikomppa** [comment]
Uh, ok.

Sorry for not responding earlier.

There's a bunch of things SoLoud could do to help tweak these kinds of things, like you can set the speaker vectors and there's at least some option to play around with the matrices, although there's at least one reported issue that requests more configurability on those parts. So there's definitely room for improvement.

**Comment by JacksonAllan** [comment]
Hi Jari. Thanks so much for responding.

To explain a little further, my laptop has some kind of driver/OS/hardware
issue that is causing the problem I described. I'm still not sure why this
is occurring, but I can confidently say that it has nothing to do with
SoLoud. My original statement that the problem didn't occur in the
OpenAL/Emscripten version of my program was incorrect - it simply hadn't
occurred *yet*.

Sorry if I wasted your time.

Also, thanks for providing a great library! There are a lot of audio
solutions out there, but I don't think there are as simple and fully
features as SoLoud (though I have tried commercial solutions like FMOD),
particularly if you need positional sound and don't want to use dynamic
linking.

All the best!
