### ISSUE TITLE
loadMem const ?

### ISSUE THREAD

**Issue by deathmock5** [jarikomppa/soloud#212]
Any chance there can be a const overload for loadMem? ie:
`loadMem(const unsigned char* data,const unsigned int len);`

Workaround for that right now is to : 

```
unsigned char* datacopy = new unsigned char[size];
memcpy(datacopy, data, size);
sample.loadMem(datacopy, size,false,true);
```

If I get the time, ill make a pull myself. But figured id bring it up first.

**Comment by jarikomppa** [comment]
There shouldn't be any reason why the loadMem pointers couldn't be const.
It's read only data in any case.

**Comment by jarikomppa** [comment]
Did the change, hoping it doesn't blow something up. It shouldn't, considering it's just syntatic sugar that can be casted away.
