### ISSUE TITLE
Compile Universal Windows App? (UWP)

### ISSUE THREAD

**Issue by Alias-777** [jarikomppa/soloud#217]
> Expected behavior:
Able to compile for Windows UWP.

> Actual behavior:
Not able to compile for Windows UWP.

> Steps to reproduce the problem:
Include SoLoud sources in a UWP project and compile. Tried with WINMM, WASAPI and SDL2 backends, all without any luck. SDL2 backends do compile but crash at runtime! The other two dont compile.

Here is a screenshot from the runtime error.
![ss](https://user-images.githubusercontent.com/34722701/58334801-8cfe6600-7e40-11e9-91f6-bac6ccd447e5.png)

> SoLoud version, operating system, backend used, any other potentially useful information:
Soloud: soloud_20181119.zip (current stable)
SDL2: Latest.
OS Windows 10 X64
Visual studio 2017

The actual code is something like this:

                sSound.init(); // a SoLoud instance;
                // sWave is a Soloud::Wav and the data is a Vorbis buffer.
                sWave.loadMem(S::assets.oggData[0].buffer, S::assets.oggData[0].length, false, false);
                sWave.setLooping(true);

                // Make 2 instances and have some fun with them
                auto h = sSound.play(sWave);
                auto h2 = sSound.play(sWave);

                sSound.setPan(h, -1);
                sSound.setPan(h2, 1);

Is Windows UWP even a supported target?

Best Regards!

[//]: # ( You don't need to follow the above template if you do not want to; feel free to start from scratch. )
[//]: # ( Following the template leads to problem reports that are helpful to the developers. )
[//]: # ( ...yes, this weird syntax is how one writes comments in a markdown file )

**Comment by jarikomppa** [comment]
I haven't done anything to especially support UWP, but I think the only
thing needed would be to write a backend that works with UWP.

**Comment by Alias-777** [comment]
Thanks for your reply!

SDL2 supports UWP including Audio see this link: https://github.com/spurious/SDL-mirror/blob/master/docs/README-winrt.md

I already have SoLoud working on Win32 and Android, both on SDL2_static backend but I really want the UWP target as wel.

It compiles but as the screenshot in my original post shows, it crashes..! Perhaps there are - unintentional - `#if (!)defined(...)` constraints in place that hinder UWP builds from working correctly.(?). (Unsure though)

I'm actually checking that right now. The problem lays in:

    void interlace_samples_float(const float *aSourceBuffer, float *aDestBuffer, unsigned int aSamples, unsigned int aChannels)

It seems that `aDestBuffer` is not allocated correctly.. Do you perhaps have any ideas on that?

Thanks.

**Comment by jarikomppa** [comment]
Try disabling the SIMD acceleration (define DISABLE_SIMD).

**Comment by Alias-777** [comment]
That results in:

`{...}\soloud\src\core\soloud.cpp(69): error C2440: '=': cannot convert from 'unsigned char *' to 'float *'`

Which is this line:
`mData = mBasePtr;`

the #else clause does just cast mBasePtr to float*... Doing that will compile it but gives the same crash.... The problem might lay in SDL_OpenAudioDevice (in sdl2static_init)... looking into that now.

**Comment by Alias-777** [comment]
When continue restarting the App it works about 1/6 times. But when it works the sound was clipping a lot. Especially on the end/restart of the sample.

How ever, when I set as.format to AUDIO_S16 instead of the default float version AUDIO_F32... It works like a charm without clipping.

So either SoLoud OR SDL is behaving differently on UWP..,  when it's configured on floats.

But is using AUDIO_S16 in any way a problem? And is there a way of forcing AUDIO_S16 by default? (judging by the code its not possible without editing sdl2static_init., it's just being used as a fallback.).

**Comment by jarikomppa** [comment]
I'd suggest using some other audio backend. MiniAudio for example seems to have robust modern windows audio interfaces, so it might work better than SoLoud's SDL backend. I'm closing this for now, as unless someone interested is willing to debug it, it won't progress.
