### ISSUE TITLE
Failed backend initializations leak resources when using SoLoud::AUTO

### ISSUE THREAD

**Issue by sammalt** [jarikomppa/soloud#219]
> Expected behavior:

When a backend initialization fails, Soloud should clean up allocated resources before moving on to initialize another backend. 

> Actual behavior:

The resources allocated in the init function of the backend are not released if it fails.

> Steps to reproduce the problem:

1. enable multiple backends
2. make first of them fail halfway through the initialization (e.g. enable WinMM backend, disable all playback devices on Windows)
-> soloud is initialized, but resources allocated by the failing backend are not released

**Comment by jarikomppa** [comment]
The winmm backend was really bad at this. wasapi is also bad, but it seems broken at the moment in any case. If there's similar issues with other backends, please do open a specific ticket.

**Comment by jarikomppa** [comment]
Oops, noticed that I've merged fix for wasapi from you, so wasapi shouldn't be 'broken' anymore. It does, however, leak resources if init fails. Since you seem to know what you're doing there, could you make a pull request fixing that?

**Comment by sammalt** [comment]
I'm a bit busy right now, but I'll see what I can do within a week or two.

**Comment by jarikomppa** [comment]
No hurry, the leaks have been there for years.. =)
