### ISSUE TITLE
getStreamPosition() does not return correct time when changing play speed

### ISSUE THREAD

**Issue by Calorado375** [jarikomppa/soloud#224]
As I have seen the mix_internal function just adds the same time to mStreamPosition than to mStreamTime. Multiplying it by mVoice[i]->mOverallRelativePlaySpeed works fine though.

Complete line: mVoice[i]->mStreamPosition += buffertime * mVoice[i]->mOverallRelativePlaySpeed

**Comment by jarikomppa** [comment]
Fixed.
