### ISSUE TITLE
Is there any minimalist audio player based on SoLoud?

### ISSUE THREAD

**Issue by cesss** [jarikomppa/soloud#225]
I'm wondering if there's any simple audio player based in SoLoud (for playing mp3 files, for example). I ask this because I used to love the ancient Vox player for Mac (there are new versions, but cannot be compared to the great minimalist player that Vox used to be), and looking at the SoLoud API, and considering the sound effects it supports, I just thought there could be a  "SoLoud+ImGui=NewVox" :-)

In case you never saw the good-old-days Vox working, you can get a glimpse [here.](https://www.youtube.com/watch?v=NHmNJV9d2BM)

**Comment by jarikomppa** [comment]
While I'm not against someone making a player based on SoLoud, I don't think it's part of this project proper. Plug SoLoud with ImGui and https://github.com/mlabbe/nativefiledialog and you're at least partway there. Whether the result is what you crave is a good question, as tastes differ.
