### ISSUE TITLE
How to play a mp3 file by the IDE such as CLion?

### ISSUE THREAD

**Issue by Tyrone-Zhao** [jarikomppa/soloud#226]
> Expected behavior:
play a mp3 file.

> Actual behavior:
I'm not good at the cmakefile.txt, so when I want to play a mp3 file by CLion, the cmakefile.txt show errors. When I tried to fix it the program is going crazy.

> Steps to reproduce the problem:
open this project with CLion

> SoLoud version, operating system, backend used, any other potentially useful information:
Latest version on OSX.

**Comment by jarikomppa** [comment]
Are you able to make SoLoud make other kinds of sounds?

**Comment by Tyrone-Zhao** [comment]
I can‘t couse I dont know how to config cmakefile.txt.



发自我的iPhone


------------------ Original ------------------

**Comment by jarikomppa** [comment]
Okay, this issue is not related to SoLoud.
