### ISSUE TITLE
Pauses between loops when looping FLAC

### ISSUE THREAD

**Issue by alekseyt** [jarikomppa/soloud#227]
> Expected behavior:

FLAC audio loops from the beginning if `setLooping(voice, true)` was called.

> Actual behavior:

There is a pause between loops equal to the track length.

> Steps to reproduce the problem:

1. Play audio source from FLAC
2. Set looping to true
3. Wait for track to (audibly) finish

Result: silence

4. Wait for another track length

Result: track actually loops and start playing again

Pseudocode:

```c++
SoLoud::Soloud soloud;
SoLoud::Wav sample;

sample.load("Sample_BeeMoved_96kHz24bit.flac");
const int voice = soloud.play(sample);
soloud.setLooping(voice, true);
```

Sample FLAC: https://helpguide.sony.net/high-res/sample1/v1/en/index.html (High-Resolution music file (96 kHz/24 bit FLAC)).

> SoLoud version, operating system, backend used, any other potentially useful information:

SoLoud: master with minor modifications
OS: Linux
Backend: SDL2

I think one manifestation of this issue is that if i call `getLength()` on audio source then i get double length, e.g. if track is 40 seconds when `getLength()` would report 80 seconds. Pause between loops also seems to be equal to track length.

I suspect number of channels is not being taken into account when counting samples and 2 channels double the length. I made this patch for `Wav::loadflac()`:

```diff
diff --git a/3rdparty/soloud/src/audiosource/wav/soloud_wav.cpp b/3rdparty/soloud/src/audiosource/wav/soloud_wav.cpp
index 1faeb48b..224ae4f6 100644
--- a/3rdparty/soloud/src/audiosource/wav/soloud_wav.cpp
+++ b/3rdparty/soloud/src/audiosource/wav/soloud_wav.cpp
@@ -229,7 +229,7 @@ namespace SoLoud
                        return FILE_LOAD_FAILED;
                }
 
-               drflac_uint64 samples = decoder->totalSampleCount;
+               drflac_uint64 samples = decoder->totalSampleCount / decoder->channels;^M
 
                if (!samples)
                {
```

and it seemingly fixes the issue. But i'm completely unsure if this is correct fix so i thought i'd ask if this is something i'm doing wrong or maybe some `drflac_` function has to be used there idk.

By the way line ending was detected as CRLF, that `^M` in patch shouldn't be there normally.

[//]: # ( You don't need to follow the above template if you do not want to; feel free to start from scratch. )
[//]: # ( Following the template leads to problem reports that are helpful to the developers. )
[//]: # ( ...yes, this weird syntax is how one writes comments in a markdown file )

**Comment by jarikomppa** [comment]
This sounds like the issue that was discussed at https://github.com/jarikomppa/soloud/pull/210 and since libraries have been updated this should be fixed now as well.
