### ISSUE TITLE
Soloud::playClocked() doesn't play audio source when passing real time to it

### ISSUE THREAD

**Issue by alekseyt** [jarikomppa/soloud#229]
> Expected behavior:

`soloud.playClocked(time, source)` plays audio source entirely

> Actual behavior:

Silent output.

> Steps to reproduce the problem:

I have branch like this (pseudocode): 

```c++
const handle voice = (isValid(pos) 
    ? soloud.play3dClocked(time, source, x, y, z)
    : soloud.playClocked(time, source));
```
`time` is real time (e.g. `1566931828.452821`), source is valid playable source.

I noticed that when code takes `playClocked()` branch audio source is not actually played. However when code takes `play3dClocked()` branch then source is played as expected.

> SoLoud version, operating system, backend used, any other potentially useful information:

SoLoud: master with minor modifications
OS: Linux
Backend: SDL2

I've compared `playClocked()` and `play3dClocked()` implementations and made this patch:

```diff
diff --git a/3rdparty/soloud/src/core/soloud_core_basicops.cpp b/3rdparty/soloud/src/core/soloud_core_basicops.cpp
index 26b025fb..466a904f 100644
--- a/3rdparty/soloud/src/core/soloud_core_basicops.cpp
+++ b/3rdparty/soloud/src/core/soloud_core_basicops.cpp
@@ -118,7 +118,7 @@ namespace SoLoud
                        mLastClockedTime = aSoundTime;
                unlockAudioMutex();
                int samples = 0;
-               if (aSoundTime > lasttime)
+               if (lasttime != 0)
                {
                        samples = (int)floor((aSoundTime - lasttime) * mSamplerate);
                }
```

This is how `play3dClocked()` handles situation when lasttime is zero. Otherwise, as far as i can tell, integer overflow occurs which leads to incorrect (negative) number of samples to play, then `mDelaySamples` is unsigned, so i assume this results in a very large delay before playing audio source.

It seemingly fixes the issue, but i'm not entirely sure how correct this patch is.

[//]: # ( You don't need to follow the above template if you do not want to; feel free to start from scratch. )
[//]: # ( Following the template leads to problem reports that are helpful to the developers. )
[//]: # ( ...yes, this weird syntax is how one writes comments in a markdown file )

**Comment by alekseyt** [comment]
I guess worth mentioning: #135. Sadly i didn't search for similar bugs in closed before submitting new one.

**Comment by jarikomppa** [comment]
I think what's happening is that somehow the number of delay samples gets really high (or negative, I guess) and while the sample will eventually be played, it may take a few years. This is not the intent, so I think a better fix would be to clamp the maximum delay... it'll be a hack, but better than completely breaking down.

**Comment by jarikomppa** [comment]
I went through the logic and rewrote the way delay samples are calculated. It should(tm) work now, even though the exact benefits can be hard to demonstrate vs simply play().

What the playclocked does is that it adds delay samples to the start of playback to avoid a bunch of instances of the same sample from playing at the exact same moment. This may sound like a bad idea, but let's consider the timeframe: if we have 2048 sample buffer at 44100, a single buffer takes about 46 milliseconds. Every time a new buffer is mixed, the delay sample count is reset to zero on the first played sound (i.e, the first one of every buffer always has 0 delay samples). Thus, delay samples are only added if you trigger more than one sound within that 46ms window.

If you trigger a sound every single frame, or 60Hz, that's ~17ms per frame - then it makes some sense; without the playclocked, you'll get 2-3 instances of the sound starting at the same time, while playclocked will space them out by, approximately, 17ms, assuming the clock source given to it is accurate enough.

(triggering a sound at 60Hz sounds horrible, though, but that's beside the point)
