### ISSUE TITLE
Issues compiling with GMake

### ISSUE THREAD

**Issue by nathanleighsays** [jarikomppa/soloud#231]
I'm unable to build the library on Ubuntu 19.04.

I get this issue both with the cloned git repository (as of 10-01-19) and the stable release on the website (soloud_20181119.zip). When I attempt to run:

genie --with-common-backends gmake

when I run make it exits saying:

../../src/backend/openal/soloud_openal_dll.c:133:8: error: expected identifier or ‘(’ before string constant
 extern "C"
        ^~~
make[1]: *** [SoloudStatic.make:389: debug/Debug/SoloudStatic/src/backend/openal/soloud_openal_dll.o] Error 1
make: *** [Makefile:33: SoloudStatic] Error 2

**Comment by jarikomppa** [comment]
Looks like a c file with c++ extern clause. If someone can just remove that line (and corresponding }) or encapsulate them with c++ #ifdef clauses and make a pull request that would be nice. I don't compile with openal myself so this has slipped by. (Why on earth would you like to use soloud through openal though is beyond me).

**Comment by lvivtotoro** [comment]
I like my extra platform support, think of the AmigaOS users :).

**Comment by jarikomppa** [comment]
If you can get SoLoud working on AmigaOS, pull request is welcome.

**Comment by lvivtotoro** [comment]
My point was that OpenAL-soft was ported to AmigaOS (partly, but AFAIK the simple stuff works), so the OpenAL backend should be enough for AmigaOS support.

**Comment by jarikomppa** [comment]
It would be a horrible support though. Chaining SoLoud with OpenAL produces huge latency.
