### ISSUE TITLE
Soloud::play() ignores volume adjustments when paused

### ISSUE THREAD

**Issue by GWRon** [jarikomppa/soloud#239]
I cue a voice for playing with Soloud::play() with paused enabled.
Later, while the voice is still paused, I adjust the volume of the voice.

When then playing it back ("unpause") the volume starts at the originally set value (`aVolume`). It then gradiently adjusts over several frames until it reaches the correct value.

I would expect the sound to be set to the desired volume without "fading" as the voice is "paused".

In my case I tried to do this:
- create a whatever voice
- decide to use it for crossfading sounds / music / ...
- so if that voice is used as "second music stream" (first fades out, second fades in meanwhile)
- so I set its volume to 0
- resuming playback/unpause leads to a "pop"-sound as for some milliseconds the original value (eg volume of 1.0) is used and gradiently fades to the desired "0.0" volume instead of starting straight at 0.0 (I would increase volume then during my crossfading process).

**Comment by jarikomppa** [comment]
I have to investigate this further, but a workaround is to start all those streams with volume 0 on the play command (e.g, gSoloud.play(gMusic1, 0, 0, 1)).

**Comment by jarikomppa** [comment]
Hm. I can't seem to reproduce this. In soloud_core_voiceops.cpp the updateVoiceVolume seems to correctly check and adjust paused voice volume to avoid the volume ramp.

Note that setVoiceVolume is an internal call. I should probably rename all those to something more obvious to avoid confusion.
