### ISSUE TITLE
calcFFT update rate

### ISSUE THREAD

**Issue by PcChip** [jarikomppa/soloud#244]
Hi,

I'm calling calcFFT() 144 times per second and displaying the results, but all I see on screen appears to be about 2-4hz  
  
How can I change the internal update frequency?

also I'm mostly getting a flat line for the higher frequencies ( https://i.imgur.com/p2dQlMc.png )  
I'm assuming I have to multiply or pow() the higher frequencies, but do you have a guideline of the correct way to do that?  
  
Thanks for any suggestions you have

**Comment by PcChip** [comment]
interestingly I found that if I initialize soloud like this:  
  
`gSoloud.init(1U, 0U, 44100, 2048);`  
  
using all default parameters instead of just init() , the FFT update rate is much faster  
  
I tried using buffer sizes of 512 and 1024 but the audio was quite choppy, even on a 5GHz 9900k

**Comment by jarikomppa** [comment]
The visualization data is captured for every block that is calculated. For the main SoLoud object this is probably something large, depending on the backend that gets chosen, like 4096, which at 44100Hz means about 10 times per second.

If you want really high frequency fft output, it might make sense to create a custom filter which goes through all the data that's processed and outputs a waterfall of fft data (without actually modifying the data).
