### ISSUE TITLE
Wrong include for SDL.h in soloud_sdl2_static.cpp?

### ISSUE THREAD

**Issue by sponji** [jarikomppa/soloud#245]
I have added SDL2 and SoLoud as submodules in my project, and there seems to be a problem that soloud_sdl2_static.cpp is including "SDL2/SDL.h", which can not be found inside SDL2's source. I think the correct include should be just "SDL.h"

My reasoning is that if I install SDL2 on my system (I don't actually want to use the installed one), `sdl2-config --cflags` says to add /usr/include/SDL2 to include directories, and that is where the SDL.h is. SDL2's CMakeLists.txt also adds `${SDL2_SOURCE_DIR}/include` to include directories, and that is where SDL.h is located in SDL2's source.

**Comment by jarikomppa** [comment]
Done on source side, build scripts probably need an update.
