### ISSUE TITLE
SOLOUD_SSE_INTRINSICS compile issue on 64 bit with MSVC

### ISSUE THREAD

**Issue by underscorediscovery** [jarikomppa/soloud#246]
Summary: SoLoud cannot be built as 64 bit with intrinsics enabled currently.

If you make a blank, empty c++ project in Visual Studio, set it to x64 architecture, and attempt to compile the following:

```c++
#include <xmmintrin.h>
#include <emmintrin.h>

int main() {
  __m64 d0 = _mm_cvtps_pi16(0);
    return 0;
}
```

You get the error `error C3861:  '_mm_cvtps_pi16': identifier not found`

This is used in soloud.cpp, inside of `interlace_samples_s16_mono`. The functions `_mm_cvtps_pi16`,  `_mm_setr_epi64` and `_mm_empty` are undefined on x64 builds.

If you go into the MSVC headers, you'll find `_M_IX86` is not defined. Therefore, these functions are not defined. If you check [this link for predefined macros](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019), it mentions

> **_M_IX86** Defined as the integer literal value 600 for compilations that target x86 processors. This macro isn't defined for x64 or ARM compilation targets.

The reason comes from [this link about __m64](https://docs.microsoft.com/en-us/cpp/cpp/m64?view=vs-2019):

> The __m64 data type is not supported on x64 processors. Applications that use __m64 as part of MMX intrinsics must be rewritten to use equivalent SSE and SSE2 intrinsics.

Any thoughts?

**Comment by underscorediscovery** [comment]
Note a work around is to disable the intrinsics just for those functions, like this or any variant that disables it:

![image](https://user-images.githubusercontent.com/236374/73404222-fd9a3400-42a5-11ea-9499-f0033a4a4e3f.png)

**Comment by WinterSolstice8** [comment]
Here is a patch file to accomplish the workaround.
[VSCx64_workaround.txt](https://github.com/jarikomppa/soloud/files/4131996/VSCx64_workaround.txt)

**Comment by jarikomppa** [comment]
Okay, apologies for breaking the build. I haven't done testing on x64 on this update pass as of yet, and I'm pretty amazed people react to the changes this fast. I've pushed a change that only enables the mmx interlacing code if _M_IX86 is defined - this will probably disable the code on more targets than is needed.. there's probably some ARM target that would work too, but it's better to be safe than sorry in this case.

**Comment by underscorediscovery** [comment]
I think the ideal is to use the SSE (instead of MMX) functions right? I haven't looked too closely at what the code is doing, but isn't it feasible to port those small handful of function calls to an SSE+ alternative?

curiously, the intel ISA guide says this is SSE but it doesn't appear to be the case considering the `__m64` usage 
![image](https://user-images.githubusercontent.com/236374/73423969-820aa800-42e2-11ea-9b13-89c99ec53212.png)

**Comment by jarikomppa** [comment]
I'm sure it's possible, but I don't have time to get into it. If you feel you're up to the task, pull requests are welcome.

**Comment by underscorediscovery** [comment]
Likewise I don't have time to dig in right now unfortunately! Thanks for the quick fix though.
