### ISSUE TITLE
Can't build cc132f1 on Linux

### ISSUE THREAD

**Issue by alekseyt** [jarikomppa/soloud#247]
> Expected behavior:

SoLoud compiles on Linux

> Actual behavior:

```
$ make
==== Building SoloudStatic (debug) ====
...
soloud.cpp
../../src/core/soloud.cpp: In member function ‘void SoLoud::Soloud::mix_internal(unsigned int)’:
../../src/core/soloud.cpp:1853:17: error: ‘_DN_FLUSH’ was not declared in this scope
      _controlfp(_DN_FLUSH, _MCW_DN);
                 ^
../../src/core/soloud.cpp:1853:28: error: ‘_MCW_DN’ was not declared in this scope
      _controlfp(_DN_FLUSH, _MCW_DN);
                            ^
../../src/core/soloud.cpp:1853:35: error: ‘_controlfp’ was not declared in this scope
      _controlfp(_DN_FLUSH, _MCW_DN);
                                   ^
```

> Steps to reproduce the problem:

```
cd build
./genie gmake
cd gmake
make
```

> SoLoud version, operating system, backend used, any other potentially useful information:

cc132f1, Linux, backed is alsa if you follow steps to reproduce, but it's actually SDL2-static, although i think it's inidependend from backed.

[//]: # ( You don't need to follow the above template if you do not want to; feel free to start from scratch. )
[//]: # ( Following the template leads to problem reports that are helpful to the developers. )
[//]: # ( ...yes, this weird syntax is how one writes comments in a markdown file )

I'm trying to update SoLoud to latest master, but it doesn't build on Linux. I don't see `_DN_FLUSH` defined anywhere in `/usr/include`, after some lurking around i've found this thread in Chromium mailing list:  https://groups.google.com/a/chromium.org/forum/#!topic/blink-reviews/138rJBBXfoA (from 2014).

They are using `#if OS(WIN) && COMPILER(MSVC)` before calling `_controlfp`, but i've found that those functions are actually defined in mingw-w64 and it indeed can be cross-compiled for Windows using mingw-w64 (GCC 9.2), however i had to undef `__STRICT_ANSI__` to make it do that.

Patch that i applied to my copy of SoLoud was:

```diff
diff --git a/include/soloud.h b/include/soloud.h
index bafb7e6..d137204 100644
--- a/include/soloud.h
+++ b/include/soloud.h
@@ -198,7 +198,9 @@ namespace SoLoud
                        CLIP_ROUNDOFF = 1,
                        ENABLE_VISUALIZATION = 2,
                        LEFT_HANDED_3D = 4,
+#ifdef WINDOWS_VERSION
                        AUDIOTHREAD_FPU_DENORMAL_FLUSH = 8
+#endif
                };
 
                // Initialize SoLoud. Must be called before SoLoud can be used.
diff --git a/src/core/soloud.cpp b/src/core/soloud.cpp
index 59d28a7..f58b1f1 100644
--- a/src/core/soloud.cpp
+++ b/src/core/soloud.cpp
@@ -1848,10 +1848,12 @@ namespace SoLoud
                        if (!once)
                        {
                                once = true;
+#ifdef WINDOWS_VERSION
                                if (mFlags & AUDIOTHREAD_FPU_DENORMAL_FLUSH)
                                {
                                        _controlfp(_DN_FLUSH, _MCW_DN);
                                }
+#endif
                        }
                }
```

I don't quite understand requirements behind this and i'm not an expert in this field, so i can't suggest a proper fix for Linux, but if this is OK-ish patch, then perhaps enum values `in soloud_c.h` also need to be adjusted accordingly.

**Comment by jarikomppa** [comment]
Rats. I did a search to make sure that the fpu call was available on Linux
too, but apparently not (?). It's an optional feature anyway and disabled
by default. I'll post a patch once I'm at a keyboard; sorry for the
inconvenience.

**Comment by jarikomppa** [comment]
Done. On further research, it would make more sense to set Denorms Are Zero on SSE wherever SSE is available.

**Comment by alekseyt** [comment]
Thank you, it builds and works on Linux. I also cross-compiled it with mingw-w64 for Windows.

I've found this: http://man7.org/linux/man-pages/man3/fenv.3.html but i really don't know what `_controlfp()` is supposed to do here, is it `fesetround(FE_TOWARDZERO)`? It says "CONFORMING TO ... C99 ...". 

Apparently MSVC has `fesetround()` too: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fegetround-fesetround2?view=vs-2019 and it seems like glibc implementation of it does SSE: https://github.com/bminor/glibc/blob/5f72f9800b250410cad3abfeeb09469ef12b2438/sysdeps/i386/fpu/fesetround.c

**Comment by jarikomppa** [comment]
The problem is not about how to round numbers, but the fact that calculating denorms (i.e, very, very small numbers that do not make any difference in audio) is very expensive. A lot of audio code adds random magic numbers to signals to avoid this. Modern cpu:s have capabilities to round them to zero whenever they exist (which is what my original change tried to do), or just to consider them zero to begin with (which is the better option, according to some benchmarks).

**Comment by alekseyt** [comment]
I've looked into Chromium, into their `setCSR()` (from linked thread). Here is the source code (https://chromium.googlesource.com/chromium/blink/+/master/Source/platform/audio/DenormalDisabler.h):

```c++
inline void setCSR(int a)
{
	int temp = a;
	asm volatile("ldmxcsr %0" : : "m" (temp));
}
```

They use it like this:

```c++
inline void disableDenormals()
{
	m_savedCSR = getCSR();
	setCSR(m_savedCSR | 0x8040);
}
```

`DenormalDisabler.h` is also under `Source/platform/audio/` and their `disableDenormals()` for Windows:

```c++
inline void disableDenormals()
{
	// Save the current state, and set mode to flush denormals.
	//
	// http://stackoverflow.com/questions/637175/possible-bug-in-controlfp-s-may-not-restore-control-word-correctly
	_controlfp_s(&m_savedCSR, 0, 0);
	unsigned unused;
	_controlfp_s(&unused, _DN_FLUSH, _MCW_DN);
}
```

so it looks relevant.

The mask that they use, the `0x8040` one, it's a magic number alright. I think what they do is setting FZ and DAZ bits to whatever value was in MXCSR: https://docs.roguewave.com/en/totalview/2019/html/index.html#page/Reference_Guide/Intelx86MXSCRRegister.html

Apparently glibc does something else in `fesetround()`, they are clearing and setting some other bits... Well, Chromium works on Linux. I don't quite like asm blocks in C++ code, but there are also `_mm_getcsr()` and `_mm_setcsr()` intrinsics and they should be available in GCC and clang (don't know about MSVC).

How do i test this? I mean, assuming there is a patch that supposedly do this stuff on Linux, how do i know if this patch really does what it's supposed to do?

**Comment by jarikomppa** [comment]
My plan is to make a SSE code block that does the the _mm_setcsr() calls. That should work for all targets, including arm ones. I'd rather not use the assembler blocks unless there's a clear, demonstrable benefit.

**Comment by jarikomppa** [comment]
Note that all of this is completely optional, and may result in some performance gains. This issue (that I closed) was due to me managing to break a build, and that issue has been solved.

**Comment by alekseyt** [comment]
I tried this:

```diff
diff --git a/3rdparty/soloud/src/core/soloud.cpp b/3rdparty/soloud/src/core/soloud.cpp
index 215a2445..519fc900 100644
--- a/3rdparty/soloud/src/core/soloud.cpp
+++ b/3rdparty/soloud/src/core/soloud.cpp
@@ -1844,7 +1844,6 @@ namespace SoLoud
                }
 #endif
 
-#ifdef _MCW_DN
                {
                        static bool once = false;
                        if (!once)
@@ -1852,11 +1851,12 @@ namespace SoLoud
                                once = true;
                                if (mFlags & AUDIOTHREAD_FPU_DENORMAL_FLUSH)
                                {
-                                       _controlfp(_DN_FLUSH, _MCW_DN);
+#if defined(SOLOUD_SSE_INTRINSICS)
+                                       _mm_setcsr(_mm_getcsr() | 0x8040); // Set FZ and DAZ bits on MXCSR
+#endif
                                }
                        }
                }
-#endif
 
                float buffertime = aSamples / (float)mSamplerate;
                float globalVolume[2];
```

I could only check that bits are set after consecutive call to `_mm_getcsr()`, but they are set and this doesn't seem to break anything on Linux.

This actually cross-compiled for OSX using clang 8, but i don't have OSX so i can't check. There was another issue with OSX build, but unrelated to this one.

Also cross-compiled for Windows with mingw-w64, also didn't check because i need to reboot for that and i'm pretty sure mingw build will work on Windows.

Sure, no probs. I'm looking forward to this, if i can somehow help to debug this - i can help.

**Comment by jarikomppa** [comment]
I've pushed change that sets DAZ/FTZ SSE flags in the audio thread. It seems to have a clear speed benefit even on my simple benchmark. (4.8 sec base, 5.1 sec with disable_simd, 4.6 sec with DAZ/FTZ)

**Comment by alekseyt** [comment]
I can confirm that this builds and works on Linux, i also cross-compiled it for OSX and Windows. Thank you very much.
