### ISSUE TITLE
CLOCK_REALTIME undeclared when cross-compiling for OSX

### ISSUE THREAD

**Issue by alekseyt** [jarikomppa/soloud#248]
> Expected behavior:

SoLoud compiles.

> Actual behavior:

```
.../soloud/src/core/soloud_thread.cpp:224:18: error: use of undeclared identifier 'CLOCK_REALTIME'
                        clock_gettime(CLOCK_REALTIME, &spec);
                                      ^
1 error generated.
```

> Steps to reproduce the problem:

I'm not sure about this, i'm using my own CMake scripts with osx-cross/clang-8 and MacOSX SDK 10.11. Target OSX version was set to 10.9 i think. I actually don't have OSX, i cross-compile just to check if it compiles for mac, this build isn't used and i don't know what happens when SoLoud is compiled in XCode or on newer OSX or whatever.

> SoLoud version, operating system, backend used, any other potentially useful information:

master with minor modifications, host OS is Linux, target is OSX, SDL2 static.

[//]: # ( You don't need to follow the above template if you do not want to; feel free to start from scratch. )
[//]: # ( Following the template leads to problem reports that are helpful to the developers. )
[//]: # ( ...yes, this weird syntax is how one writes comments in a markdown file )

Maybe it's not an issue, but there are some posts on this topic. 

Potential patch:

```diff
diff --git a/src/core/soloud_thread.cpp b/src/core/soloud_thread.cpp
index d3dbe4f..5adcc44 100644
--- a/src/core/soloud_thread.cpp
+++ b/src/core/soloud_thread.cpp
@@ -28,7 +28,7 @@ freely, subject to the following restrictions:
 #include <inttypes.h>
 #include <pthread.h>
 #include <unistd.h>
-#include <time.h>
+#include <sys/time.h>
 #endif
 
 #include "soloud.h"
@@ -220,9 +220,9 @@ namespace SoLoud
 
                int getTimeMillis()
                {
-                       struct timespec spec;
-                       clock_gettime(CLOCK_REALTIME, &spec);
-                       return spec.tv_sec * 1000 + (int)(spec.tv_nsec / 1.0e6);
+                       struct timeval val;
+                       gettimeofday(&val, NULL);
+                       return val.tv_sec * 1000 + (int)(val.tv_usec / 1000);
                }
 #endif
```

With this patch it builds for both Linux and OSX, i only checked that build for Linux isn't broken, didn't check OSX build.

**Comment by jarikomppa** [comment]
I don't want to use timeofday in general. A separate code block that only compiles on osx would be a better solution.

**Comment by alekseyt** [comment]
Hmmm. I wouldn't risk to do non-portable change because i don't have OSX and can check. Right now there is exactly one issue with cross-compiling which is clear, has detailed description and intended resolution. If i just add some code then there might be 10 subtle issues in random places. I don't want to make life of OSX folks harder than it is.

Please allow me to close this. I see your point, i resolved this locally with a workaround and i don't see this as an issue anymore. It should be searchable by "CLOCK_REALTIME" if this issue is real and affects anyone besides me, so it doesn't really matter if it's open or closed.

**Comment by underscorediscovery** [comment]
[I'll link this as it may be of interest](https://github.com/snowkit/linc_timestamp/blob/master/linc/linc_timestamp.cpp#L41-L53), some older lib of mine (MIT). It returns high resolution time on macOS in seconds. 

```cpp
#if macos

  double now_in_seconds() {

    static double time_scale = 0.0;

    if (time_scale == 0.0) {
      mach_timebase_info_data_t info;
      mach_timebase_info(&info);
      time_scale = 1e-9 * (double)info.numer / info.denom;
    }

    return mach_absolute_time() * time_scale;

  }
#endif

```

Also worth bringing up is std::chrono if using c++11 on your local end, you can ask it for a high res timer.
