### ISSUE TITLE
Invalid code generated in soloud.py

### ISSUE THREAD

**Issue by pvcraven** [jarikomppa/soloud#249]
Expected behavior:

Build script creates a soloud.py with Python code that can run.

Actual behavior:

On line 2457 of soloud.py in the zipped release 20200207 we have this:
`def set_params(self, aHardwareChannels, aWaveform = SoLoud::Misc::WAVE_SQUARE):`

Those double colons are not valid Python. Not sure what is supposed to go there.

**Comment by pvcraven** [comment]
I got this library to work with Python 3.7 under Windows. Is there documentation on how to create libraries for MacOS and Linux that can work for Python?

**Comment by jarikomppa** [comment]
Fixed in 54a93ef280b216bc577ddeecf28728093a10e359

Things should(tm) work the same way on linux and osx, by building the dynamic link library (.so on those platforms). The way the python code works, it doesn't explicitly state ".dll" for the dynamic link library. There's a potential hitch for x86 vs x64 versions though; the python wrapper tries to open "soloud_x86", so it's presumed that the python is x86 too...

**Comment by pvcraven** [comment]
Hate to ask stupid questions, but what is the easiest way to build it as a library under Linux and MacOS?

**Comment by jarikomppa** [comment]
Not a stupid question as such. I'd get GENie and generate project files (unix makefiles should do fine), and run make. Someone did contribute cmakefiles, they're under contrib - but I haven't tried them.

**Comment by pvcraven** [comment]
Ok, I have:

* Cloned soloud.py on Linux
* Cloned genie on linux
* Build genie
* Run genie on soloud asking it to create gmake files
* Build via gmake (while installing needed libraries)
* Now have a lot of object files

Is there an option for generating a .so or something I should do to create this?

**Comment by jarikomppa** [comment]
The genie-generated makefiles should(tm) build the static and dynamic
libraries. I've never done this on linux or osx though, I've always just
included the needed files to my projects on linux, and I don't use osx
myself.

**Comment by pvcraven** [comment]
For build options I guessed: `../../genie/bin/linux/genie --with-openal --with-portaudio gmake` (not at all sure what I should use) and a `make` in the gmake folder creates a lot of `.o` but no `.so` files.

I'm really hoping I can get a Python front-end working with this on linux/mac/windows as cross-platform sound is so lacking in Python.

**Comment by pvcraven** [comment]
Oh, I had to build with the release config.

**Comment by pvcraven** [comment]
Progress I think:

``SoLoud dynamic link library (linux_x86.so on Linux) not found. Terminating. libraries/libsoloud.so: undefined symbol: snd_pcm_close``

**Comment by pvcraven** [comment]
I'm still totally stuck on this step. The snd_pcm_close is from ALSA which I guess means I'm not linking in the ALSA library correctly? Or do I have to somehow load the ALSA library in linux before loading SoLoud?

**Comment by pvcraven** [comment]
Ok, looks like ALSA needs to first be imported with:
```
		sharedlib = ctypes.CDLL("libasound.so", mode=ctypes.RTLD_GLOBAL)
		soloud_dll = ctypes.CDLL("libraries/libsoloud.so")
```
