### ISSUE TITLE
No obviousway to reuse voice handles

### ISSUE THREAD

**Issue by Keithcat1** [jarikomppa/soloud#252]
So, let's say I play a sound.
I can set pan, pause, loop, ETC until the sound is finished.
Then there is no way to use that voice handle anymore and get a peep out of it.
I would have to copy all attributes to a new voice and then use that.
Could you add a restart function or a way to quickly seek to 0?
Thanks!

**Comment by jarikomppa** [comment]
The handles are meant to be used and discarded. Just play again when you need to? 

What's your exact use case?

**Comment by jarikomppa** [comment]
Some (but not all) audio sources do actually support rewinding, so if you do soloud.seek(voicehandle, 0); it will rewind the stream to the beginning. If the audio has ended, however, it's already discarded. To avoid that, you'd need to make the sound loop, but that's probably not what you want, either.

Thus, I'm curious what the use case is; it's possible we need some new feature to support it, or it's possible it already exists.

**Comment by Keithcat1** [comment]
I'm making a sound class which allows me to manage playback of a single sound file.
My issue is that handles don't work anymore after the sound has finished playing.
I need to have a constant handle.
I can't just call play again because all sorts of effects which were previously set on the handle will be removed.
I'd have to copy the values like pan , volume, looping ETC.
I guess what I want is a way to prevent a handle from expiring.
Hope that's understandable.

**Comment by jarikomppa** [comment]
If this is a wave sound file, you can set it to loop and then set the loop offset near the end, assuming there's a bit of silence at the end of the file. That will stop it from expiring. Not the most elegant solution, sure, but should work.

**Comment by Keithcat1** [comment]
I have no way to tell if there is silence there or not.
These files could be in any format and will come from anywhere.

**Comment by jarikomppa** [comment]
I presume you're making a media player of some sort. This is not what SoLoud is meant for, but feel free to try.

I've added setAutoStop() for audio sources, which you can use to disable the automatic stopping of sounds when they end. Using this in general is a bad idea, because it will keep reserving the output voices for these sounds, but it may help in your use case.

**Comment by Keithcat1** [comment]
Very cool, thanks!
However, it seems that you forgot to run codegen. I can't run it myself, as it loves to crash.
Also, could you add a restart method that quickly seeks back to 0? Or can I do that myself? I thought that the seek operation is relative, by which I mean it seeks forward by the number of seconds passed. That said, seeking to 0 wouldn't work.
Could you add soloud_c.cpp to the genie.lua file so that it is compiled into the static library by default?
Also, SoloudDynamic cannot be linked with Ninja. First, an invalid /DEF option is passed, I guess that's for visual studio. Second, it forgets to link with winmm.
Thanks for looking at all this!

**Comment by jarikomppa** [comment]
You have a lot of demands =)

Seeking is not relative. Seeking to zero will (in the audio sources that support it) restart the stream from beginning.

I don't update the generated codes on every update. What do you mean codegen likes to crash?

Finally, I'm not responsible for what ninja does. You can always use visual studio to compile in windows.

**Comment by Keithcat1** [comment]
Lolol sorry.
Good to know, the sources I'm using are WavStream and Wav. I'm sure I can make it work.
As for codegen...

C:\Users\Keith\Downloads\soloud\src\tools\codegen>g++ -Ofast -w -s -omain.exe ma
in.cpp

C:\Users\Keith\Downloads\soloud\src\tools\codegen>main.exe
SoLoud C-Api Code Generator (c)2013-2020 Jari Komppa http://iki.fi/sol/

This program will generate the 'C' api wrapper code.
You probably ran this by mistake.
Use parameter 'go' to actually do something.

Note that output will be ../include/soloud_c.h and ../src/c_api/soloud_c*.cpp.


C:\Users\Keith\Downloads\soloud\src\tools\codegen>main.exe go
SoLoud C-Api Code Generator (c)2013-2020 Jari Komppa http://iki.fi/sol/
Parsing ../include/soloud.h..
Parsing ../include/soloud_audiosource.h..
Parsing ../include/soloud_bassboostfilter.h..
Parsing ../include/soloud_biquadresonantfilter.h..
Parsing ../include/soloud_bus.h..
Parsing ../include/soloud_dcremovalfilter.h..
Parsing ../include/soloud_echofilter.h..
Parsing ../include/soloud_fader.h..
Parsing ../include/soloud_fft.h..
Parsing ../include/soloud_fftfilter.h..
Parsing ../include/soloud_filter.h..
Parsing ../include/soloud_flangerfilter.h..
Parsing ../include/soloud_freeverbfilter.h..
Parsing ../include/soloud_lofifilter.h..
Parsing ../include/soloud_monotone.h..
Parsing ../include/soloud_noise.h..
Parsing ../include/soloud_openmpt.h..
Parsing ../include/soloud_queue.h..
Parsing ../include/soloud_robotizefilter.h..
Parsing ../include/soloud_sfxr.h..
Parsing ../include/soloud_speech.h..
Parsing ../include/soloud_tedsid.h..
Parsing ../include/soloud_vic.h..
Parsing ../include/soloud_vizsn.h..
Parsing ../include/soloud_wav.h..
Parsing ../include/soloud_waveshaperfilter.h..
Parsing ../include/soloud_wavstream.h..
Handling inheritance..
It crashes with a "This program is not responding" message right after that.
I tried with vs2019 and no luck.
C:\Users\Keith\Downloads\soloud\src\tools\codegen>

**Comment by Keithcat1** [comment]
Oh. Ran it from src and it worked.

**Comment by Keithcat1** [comment]
I was only able to seek to 0 and have the file play when I used the Wav source, not the WavStream source.
Checking the stream position returned 0 in both cases, but only Wav made any sound.
Thanks.

**Comment by Keithcat1** [comment]
It works if I seek to 0 immediately after the sound finishes.
As a test, I let my app sleep 500 extra milliseconds, and it stopped working.

**Comment by jarikomppa** [comment]
Can't repro, streaming ogg files at least. Only way I could get stopVoice_internal to trigger was by launching enough sounds that I ran out of virtual voices, and that took a while.

**Comment by Keithcat1** [comment]
1: Init Soloud
2: Create a WavStream
3: Load a file
4: Play it
5: Set the handles autoStop to true
6: Wait for the sound to finish
7: Sleep for 500 or more milliseconds. The bug will not reproduce if you don't
8: Seek the handle to 0.
9: Wait for the handle to finish.

**Comment by jarikomppa** [comment]
Autostop is the default state. You want to set the autostop to false.

**Comment by Keithcat1** [comment]
Ah. Clearly someone ;) has not been paying attention.
