### ISSUE TITLE
miniaudio backend segfault with simd

### ISSUE THREAD

**Issue by woollybah** [jarikomppa/soloud#253]
Hallo,

I'm currently experimenting with integrating the miniaudio backend as an alternative to the SDL2 backend I'm using in [BlitzMax](https://github.com/bmx-ng/audio.mod).

On Windows 64-bit, I'm getting a segfault using miniaudio with SIMD enabled:
```
SoLoud::panAndExpand (aVoice=0x22fb5a0, aBuffer=0x3965ff0,
    aSamplesToRead=441, aBufferSize=441, aScratch=0x3945fb0, aChannels=2)
    at D:/000_programming/BlitzMaxNG/mod/audio.mod/soloud.mod/soloud/src/core/soloud.cpp:1133
1133                                                    __m128 c1 = _mm_mul_ps(f1, p1);

(gdb) bt

#0  0x0000000000438d01 in SoLoud::panAndExpand(SoLoud::AudioSourceInstance*, float*, unsigned int, unsigned int, float*, unsigned int) ()
#1  0x00000000004392f8 in SoLoud::Soloud::mixBus_internal(float*, unsigned int, unsigned int, float*, unsigned int, float, unsigned int, unsigned int) ()
#2  0x000000000043a120 in SoLoud::Soloud::mix_internal(unsigned int) ()
#3  0x000000000043a628 in SoLoud::Soloud::mix(float*, unsigned int) ()
#4  0x00000000004259fe in ma_device_main_loop__wasapi(ma_device*) ()
#5  0x000000000040962b in ma_worker_thread(void*) ()
```
The static SDL2 works fine (with SIMD), and miniaudio appears to be okay if I disable SIMD.

Of course it may be that I've built or used something incorrectly, but I thought I'd raise this just in case there is an underlying issue.

> Expected behavior:

Audio plays using miniaudio backend with the default configuration.

> Actual behavior:

Crash with no audio when SIMD is enabled. Disabling SIMD gets audio playing.

> SoLoud version, operating system, backend used, any other potentially useful information:

Version : Recent master.
OS/build : Windows 10, 64-bit.
Backend : Miniaudio
Opts : `-msse3 -DWITH_SDL2_STATIC -DWITH_MINIAUDIO -DNDEBUG -DTHREADED  -m64 -ffast-math -fno-exceptions -c -O3`

[//]: # ( You don't need to follow the above template if you do not want to; feel free to start from scratch. )
[//]: # ( Following the template leads to problem reports that are helpful to the developers. )
[//]: # ( ...yes, this weird syntax is how one writes comments in a markdown file )

**Comment by jarikomppa** [comment]
Please see https://github.com/jarikomppa/soloud/issues/251
If you can verify that feb7b672608a067424e2e74d7f9af87e3e7d347b fixes it, it would be nice (just grab the head and test)

**Comment by woollybah** [comment]
That sorted it. Thanks! :)

**Comment by jarikomppa** [comment]
What cpu do you have? I'm trying to figure out how to reproduce this, as this probably won't be the last sse optimization thingy.

**Comment by woollybah** [comment]
It's an **i7-7700HQ**, and on Windows I am building with **GCC 8.1.0** (mingw-w64)

**Comment by jarikomppa** [comment]
Common thread seems to be gcc on mingw, but the same binaries work on some machines but not on others. Oh well. Thanks.
