### ISSUE TITLE
Exception handler (C#)?

### ISSUE THREAD

**Issue by EliasM108** [jarikomppa/soloud#257]
Can we get an exception handler for the soloud object for every time it crashes?

**Comment by jarikomppa** [comment]
That sounds like it crashes a lot. Can you give me an example code snippet so I can add it to the code generator?

**Comment by EliasM108** [comment]
I have two Global SoLoud Instances and two WaveStreams.
SoLoud.Soloud soundout = new SoLoud.Soloud();
SoLoud.WavStream Trackfile = new SoLoud.WavStream();

SoLoud.Soloud soundout1 = new SoLoud.Soloud();
SoLoud.WavStream Trackfile1 = new SoLoud.WavStream();

Then I initialize the two "soundouts" at window loaded event. That's where the crash occurs. If i remove the second initialization, everything is fine.
soundout.init();
soundout1.init();

The rest is just simple code playing music.

**Comment by jarikomppa** [comment]
You don't, ever, need more than one soloud object.

**Comment by EliasM108** [comment]
So how am i supposed to wait for each trackfile to end?
Currently i am using:
            Trackfile.loadMem(memoryPointer, (uint)file.Length, 0, 1);
            Task.Run(async() =>
            {
                uint handle = soundout.play(Trackfile);
                while(soundout.getActiveVoiceCount() > 0) { await Task.Delay(100); }
                MessageBox.Show("finished");
            });

**Comment by EliasM108** [comment]
Solved the problem with waiting till finished by using TrackFile.GetLength() and soundout.getStreamPosition(handler).
