### ISSUE TITLE
Freeverb setParam doesn't change parameters.

### ISSUE THREAD

**Issue by janEntikan** [jarikomppa/soloud#316]
Bit of a newbie here, beware there is a good chance this is my own wrong-doing. 

I'm trying to set the freeverb's parameters but no matter what values I pass the effect stays the same. Here's the code I'm using. Note that setting parameters on other filters (like Echo) seem to work fine for me.  
```
#include <cstdio>
#include "soloud/soloud.h"
#include "soloud/soloud_speech.h"
#include "soloud/soloud_freeverbfilter.h"
#include "soloud/soloud_thread.h"

int main() {
    SoLoud::Soloud gSoloud;
    SoLoud::Bus gBus;
    SoLoud::Speech gSpeech;
    SoLoud::FreeverbFilter gFreeverb;

    gBus.setFilter(0, &gFreeverb);

    float frozen = 0;
    float room_size = 0.1;
    float damp = 0.1;
    float width = 1;

    printf("Setting reverb: %d\n",gFreeverb.setParams(frozen, room_size, damp, width));

    gSpeech.setText("I like peanutbutter and jelly sandwiches");
    gSpeech.setParams(2600, 14, 2, KW_SAW);

    gSoloud.init();
    gSoloud.play(gBus);
    gBus.play(gSpeech);

    while (gSoloud.getActiveVoiceCount() > 0) {
        SoLoud::Thread::sleep(1);
    }

    gSoloud.deinit();
    return 0;
}

```

**Comment by Green-Sky** [comment]
You are changing the values for the Filter AFTER the Filter-Instance has been created. You either want to call `gFreeverb.setParams()` before gBus.setFilter(0, &gFreeverb), OR if you want to be able to change Filter parameters on the fly, so on a Instance, you need to go through `gSound.setFilterParameter()`. iirc
