### ISSUE TITLE
How to compile with GENie?

### ISSUE THREAD

**Issue by TheBoneJarmer** [jarikomppa/soloud#335]
> Expected behavior:

Get the whole source compiled using make, which is generated by cmake, which is generated by genie

> Actual behavior:

Make does nothing. No output, nada.

> Steps to reproduce the problem:

1. git clone git@github.com:jarikomppa/soloud.git
2. cd soloud
3. cd build
4. genie cmake
5. cmake .
6. make

I have never worked with GENie before. Never heard of it either. I have always up till now worked with cmake, which basically just works. I have however not a single clue how to get this up 'n running with GENie though. It looks nice and clean so far but it lacks crucial documentation on how to actually use the damn thing. Any assistance would be greatly appreciated!

With kind regards,
TheBoneJarmer

**Comment by jarikomppa** [comment]
I don't know if genie supports cmake. You can use genie to generate makefiles directly, no need to go through cmake.
If you want to use cmake, there's a cmakefile under 'contrib' - I don't know if that works, though, as it's not something I support personally.

**Comment by TheBoneJarmer** [comment]
I did not knew I could generate a makefile directly. And that is eventually what I am trying to achieve. Could you therefore share the steps I have to take in order to generate a makefile? Because that would be greatly appreciated!

**Comment by jarikomppa** [comment]
If genie is too complicated, it's best to just include the SoLoud files in your project. See:
http://sol.gfxile.net/soloud/quickstart.html

**Comment by TheBoneJarmer** [comment]
Including the entire source is no option for me. That said, GENie is not looking too complicated. It is just, I need to know the right steps to build this repo. With cmake this used to be clear for me but I cannot find any documentation concerning GENie at all. A lot about the lua scripting part but now how to properly use the CLI. 

And with above steps I do not get the desired result since my makefile seems to do nothing. Which is why I would like to know if I am running GENie in the wrong place or with the wrong arguments or something else. I get it, it may be exhausting to have to explain a tool that you think is straightforward. But for me it is not and I know  that I am not the only one. And it is rather frustrating.

**Comment by jarikomppa** [comment]
I actually tried looking around and could not find *any* genie tutorial to point at, which is curious.

Anyway, if you run genie without parameters in the `soloud/build` directory you should get commandline help. The `soloud_devel.bat` shows the parameters I use to quickly build the development environment I usually use.

Typically you'd use something like:
```genie --platform=x64 --with-miniaudio vs2017```

If you want generic gnu makefiles, replace the `vs2017` with `gmake`.

**Comment by TheBoneJarmer** [comment]
Sweet, thanks a lot! Will give that a try.

**Comment by TheBoneJarmer** [comment]
Ok, running the above instructions generated a gmake folder. And running make within the gmake folder successfully built soloud and generated binary files. Thanks a lot!
