### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by jarikomppa** [jarikomppa/soloud#35]
Currently, the SoLoud api has no mechanism for error reporting. Design and implement a non-invasive mechanism. Exceptions can't be used.

**Comment by samysadi** [comment]
There is some incoherence in the way errors are handled.
Let's take the Soloud::play() as an example.
This one returns a handle on success, and on error it returns, for instance, SoLoud::UNKNOWN_ERROR which is 7.
So you cannot distinguish between a valid handle whose value is 7 and the actual error.
In this particular case you should return 0 instead.
