### ISSUE TITLE
There is an annoying min macro inside minwindef.h that's conflicting with glm::min function 

### ISSUE THREAD

**Issue by Infinitusvoid** [jarikomppa/soloud#360]
When I import 

```
#include "soloud.h"
#include "soloud_wav.h"

void theIssue() {
	glm::vec3 a(1.0f, 1.0f, 1.0f);
	glm::vec3 b(2.0f, 2.0f, 2.0f);
	glm::min(a, a);
}
```

if I don't import works
```
//#include "soloud.h"
//#include "soloud_wav.h"

void theIssue() {
	glm::vec3 a(1.0f, 1.0f, 1.0f);
	glm::vec3 b(2.0f, 2.0f, 2.0f);
	glm::min(a, a);
}


```

min macro is inside minwindef.h
minwindef.h is located at C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared

```
#ifndef min
#define min(a,b)            (((a) < (b)) ? (a) : (b))
#endif

and it's conflicting with the 
glm::min function 
```

What do you suggest how should I deal with it ?

**Comment by Green-Sky** [comment]
Yea, soloud should not include windows.h in any public header.
as a workaround you can define `NOMINMAX` for the project
or just before all includes of soloud
```
#define NOMINMAX
```

**Comment by Infinitusvoid** [comment]
> Yea, soloud should not include windows.h in any public header. as a workaround you can define `NOMINMAX` for the project or just before all includes of soloud
> 
> ```
> #define NOMINMAX
> ```

Thanks this helped with #define NOMINMAX everyhing is ok thanks !

```
#define NOMINMAX
#include "soloud.h"
#include "soloud_wav.h"

void theIssue() {
	glm::vec3 a(1.0f, 1.0f, 1.0f);
	glm::vec3 b(2.0f, 2.0f, 2.0f);
	glm::min(a, a);
}
```
