### ISSUE TITLE
Build System is Broken in Multiple Ways

### ISSUE THREAD

**Issue by brosasaki** [jarikomppa/soloud#373]
> Expected behavior:
It is quick and simple to prepare functioning dynamic and static libraries, regardless of system.

> Actual behavior:
Me and several people on IRC have spent an entire evening trying to get a working library of either type with the C API intact. We have found several issues:
- The genie build system builds cmake files (!?) that do nothing, as in the final makefiles have no effect on the project's files at all and produce no output or error.
- The makefiles made directly by genie are able to produce a static library, but not a dynamic one.
- The genie.lua file specifically excludes the C API from the static library (???), corroborated by the absence of symbols matching the C API header in the `.a` static library.
- The genie.lua file has strange defaults which are unaware of the fact that e.g. `SDL.h` is really located in `...include/SDL/SDL.h`.
- The demos, which are built all in the same build process as the libraries (??) reference libraries not included by the build process, specifically GLEW and `GL.h`. This results in the build process for the libraries being roadblocked by the demos' broken build process(??).
- The `soloud-config.cmake` file produced by the build process is missing the location of the C API header file.

> Steps to reproduce the problem:
- Download and extract the latest release.
- Use genie to generate a set of cmake or gmake files and attempt to create a static or dynamic library with a functioning C API.

> SoLoud version, operating system, backend used, any other potentially useful information:
SoLoud 20200207, MacOS v12.7.5, N/A

[//]: # ( You don't need to follow the above template if you do not want to; feel free to start from scratch. )
[//]: # ( Following the template leads to problem reports that are helpful to the developers. )
[//]: # ( ...yes, this weird syntax is how one writes comments in a markdown file )

**Comment by jarikomppa** [comment]
There's cmake files under "contrib". As for genie issues, it might be more fruitful to complain to the genie project.

**Comment by brosasaki** [comment]
Yes, actually, I was able to compile both static and dynamic libraries fine from the git directory using the contrib Make files; it may be time to cut a new release, since the last one is so broken, though.
