### ISSUE TITLE
64-bit builds

### ISSUE THREAD

**Issue by viktorpopp** [jarikomppa/soloud#376]
I am just confused that the .sln files generated do not contain a 64-bit platform. I would really request it because I am making a 64-bit game engine, and SoLoud is the best I have found. If I am doing something wrong, please help.

**Comment by jarikomppa** [comment]
genie calls them x64 builds.

genie --platform=x64 vs2017

**Comment by jarikomppa** [comment]
(although, more optimally, you'd just drop the needed source files to your project)

**Comment by viktorpopp** [comment]
**Thanks**
