### ISSUE TITLE
Dynamic library can't be created

### ISSUE THREAD

**Issue by tapir** [jarikomppa/soloud#68]
Gives this error:

==== Building SharedLib (debug) ====
Creating debug/Debug/SharedLib
soloud_c.cpp
Linking SharedLib
../../lib/libsoloud_x86_d.so: file not recognized: File truncated
collect2: error: ld returned 1 exit status
SharedLib.make:85: recipe for target '../../lib/libsoloud_x86_d.so' failed
make[1]: **\* [../../lib/libsoloud_x86_d.so] Error 1
Makefile:32: recipe for target 'SharedLib' failed
make: **\* [SharedLib] Error 2

**Comment by jarikomppa** [comment]
Any idea whether this is still an issue?

**Comment by tapir** [comment]
No idea unfortunately

**Comment by jarikomppa** [comment]
Well, I'll close it for the time being then.
