### ISSUE TITLE
Possible sdl2 support?

### ISSUE THREAD

**Issue by cbaggers** [jarikomppa/soloud#74]
Was massively excited and tried to get this working under linux, however my project is sdl2 based. Turns out it got too giddy and didnt read the doco. 
Shame as this is easily the nicest library for this I have found so far.
Thanks for your awesome work.
Are you thinking of porting this to sdl2?

**Comment by jarikomppa** [comment]
Huh, as far as I know it should work with sdl2 as is. If something is broken, it shouldn't be too hard to fix..

**Comment by neilogd** [comment]
I've had issues with getting it running with SDL2 on Linux. Had to link in SDL & SDL2 to quickly get it working for me. Was going to look into it further, I had quite a bit of difficulty getting it to work at all on Linux with both SDL2 and Portaudio. I may be able to get onto this at some point soon (perhaps this weekend coming) and get some tidied up pull requests to fix up the Linux support.

**Comment by jarikomppa** [comment]
Are you using static of dynamic linking?

**Comment by neilogd** [comment]
I was using static linking. Building up with SDL removed from my build scripts.

**Comment by neilogd** [comment]
I build SoLoud up myself as part of my build process, script is basically a copy of your own with a few minor changes. Link errors I get if I link SDL2, and not SDL:

../../Build/gmake-linux64-clang/bin/libExternal_SoLoudDebug.a(soloud_sdl_nondyn.o): In function `SoLoud::soloud_sdlnondyn_lockmutex(void*)':
/home/neilo/Dev/PsybrusDev/GGJ2015Game/Projects/gmake-linux-clang/../../Psybrus/External/SoLoud/src/backend/sdl_nondyn/soloud_sdl_nondyn.cpp:67: undefined reference to `SDL_mutexP'
../../Build/gmake-linux64-clang/bin/libExternal_SoLoudDebug.a(soloud_sdl_nondyn.o): In function `SoLoud::soloud_sdlnondyn_unlockmutex(void*)':
/home/neilo/Dev/PsybrusDev/GGJ2015Game/Projects/gmake-linux-clang/../../Psybrus/External/SoLoud/src/backend/sdl_nondyn/soloud_sdl_nondyn.cpp:72: undefined reference to `SDL_mutexV'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../../Dist/GGJ2015Game-gmake-linux-clang-Debug] Error 1
make: *** [GGJ2015Game] Error 2

**Comment by jarikomppa** [comment]
Yeah, the nondyn needs to be made separately for sdl2. Luckily it's fairly
similar to the sdl1 nondyn..

**Comment by lilmike** [comment]
Has this been fixed? I ask because I'm having the same problem, I'm trying to staticly link sdl2, and as sdl1 is under the lgpl and my product will be proprietary, sdl2 is my only option. I didn't want to just use native backends for complicated reasons, but sdl2 would be great.
-Michael.

**Comment by jarikomppa** [comment]
Hi, I'm currently quite busy with other things, but I pushed a "blind" fix
- unless I typoed something, it should work. Let me know if that helped.

**Comment by lilmike** [comment]
Hi,
I can't figure out what you changed to give an explanation of why it's not working (why git diff isn't working I don't know, but...) so all I can say is that I just cloned the repo back to my  PC, compiled soloud, and it still complains about SDL_mutex[P,V]. I had a quick look at soloud_sdl_nondyn.cpp, and it still looks like you're using those functions... but like I said, I can't even see if that's the file that was changed anyway.
-Michael.

**Comment by jarikomppa** [comment]
There's a new sdl2_nondyn now, you should use that.

**Comment by lilmike** [comment]
Hi,
Ah. I missed that, I'll give it a go and let you know how it works out.
-Michael.

**Comment by Dids** [comment]
Function "sdl2nondyn_init" doesn't seem to exist, or there might've just been a typo in your latest commit.

**Comment by jarikomppa** [comment]
Are you sure either your project includes
backend/sdl2_nondyn/soloud2_nondyn.cpp, or you have regenerated the library
build files with --with-sdl2nondyn-only ?

**Comment by Dids** [comment]
Heh, I was actually using the wrong backend. I tried using the dynamically linked SDL backend first (latest release of SoLoud, not the latest source), and while I could compile it just fine, I got no audio output from any WAV's I tried it play.

I just tried the sdl2_nondyn backend and using WITH_SDL2_NONDYN, but ran into issues with "SDL2.h" not existing (it's SDL.h in the official libsdl 2.x source). Tried renaming to just SDL.h, but the same issue(s) exist, apart from the new audiomixer error.

error C3861: 'sdl2nondyn_init': identifier not found
error C2065: 'soloud_sdlnondyn_audiomixer' : undeclared identifier

**Comment by jarikomppa** [comment]
Sorry for the inconvenience (and this would definitely be faster if I'd
just set this thing up here); pushed fix for those two error messages.

**Comment by Dids** [comment]
Thanks! Just had to (again) rename SDL2.h to SDL.h in soloud_sdl2_nondyn.cpp, and the non-dynamic SDL2 version compile without a hitch!

I'm still, however, not hearing any audio. I was previously using SDL_mixer, but since it doesn't have good automatic cleanup, I found SoLoud and got excited, but can't seem to figure out what's wrong.

WAV file path is good, and I'm initializing/deinitializing SoLoud::SoLoud as a global pointer inside a singleton class, then feeding it a a new SoLoud::Wav each time I want to play a sound. Is there something wrong with using the library like this?

**Comment by jarikomppa** [comment]
Can you do a http://codepad.org/ paste of the source? (or gist, or email
me, or something)

**Comment by Dids** [comment]
Here's more or less the entire class: http://codepad.org/nPXfIyS2

**Comment by jarikomppa** [comment]
You create the gWave object in stack, and it gets destroyed (and thus
stopped) when the function returns.

**Comment by Dids** [comment]
Ah, duh, my bad! It's working perfectly now. :smiley:

**Comment by jarikomppa** [comment]
Have a nice day =)
