### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by Doedelzak** [jarikomppa/soloud#75]
I put the DLL and soloud.py files in my python project folder. I created a "test.py" file with the sample code provided in the Python API page on SoLoud website (the Python code of course, not the C++)

I got this message : "SoLoud dynamic link library (soloud_x86.dll on Windows) not found. Terminating." I tried to put my folder at different locations, rename it, etc. The needed files are in it, so I don't know what to do. 

I'm on Windows 7 Professional Service Pack 1. I tested the script with Python 3.3 and 2.7.

**Comment by jarikomppa** [comment]
Is the soloud_x86.dll in the same directory as your .py file?

**Comment by Doedelzak** [comment]
Thanks for your reply ! Yes, it's in the same directory.

2015-02-28 14:14 GMT+01:00 Jari Komppa <notifications@github.com>:

**Comment by jarikomppa** [comment]
Make sure the msvcr100.dll is also in the same directory.

**Comment by Doedelzak** [comment]
It wasn't and I put it... but I got the same message.

2015-02-28 19:24 GMT+01:00 Jari Komppa <notifications@github.com>:

**Comment by jarikomppa** [comment]
Running with python 2.7.6, if I have msvcr100.dll, soloud_x86.dll,
soloud.py, and test_python.py (all from the same soloud zip file) in one
directory, the test_python.py works.

**Comment by Doedelzak** [comment]
Fixed ! The problem was Python 2.7.8 : apparently, it is not compatible.

I installed Python 2.7.6 and it works. Thanks !

2015-03-01 16:20 GMT+01:00 Jari Komppa <notifications@github.com>:

**Comment by jarikomppa** [comment]
There should be no such change in python - you probably tried to use a
64bit python with the 32bit dll.
