### ISSUE TITLE
Compilation warnings 64 bit / Visual Studio 2013

### ISSUE THREAD

**Issue by petrihakkinen** [jarikomppa/soloud#85]
I get the following compilation warnings when compiling a 64-bit build with VS 2013:

soloud_fft.cpp(109): warning C4334: '<<' : result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
soloud_fft.cpp(232): warning C4334: '<<' : result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
soloud_fft.cpp(304): warning C4334: '<<' : result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
soloud_file.cpp(56): warning C4267: 'return' : conversion from 'size_t' to 'unsigned int', possible loss of data
soloud_file.cpp(98): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\stdio.h(211) : see declaration of 'fopen'
soloud_wavstream.cpp(401): warning C4267: 'initializing' : conversion from 'size_t' to 'int', possible loss stb_vorbis.c(4376): warning C4244: 'return' : conversion from '__int64' to 'int', possible loss of data
stb_vorbis.c(4386): warning C4244: 'return' : conversion from '__int64' to 'int', possible loss of data
stb_vorbis.c(4406): warning C4244: 'return' : conversion from '__int64' to 'int', possible loss of data
stb_vorbis.c(4429): warning C4244: '=' : conversion from '__int64' to 'int', possible loss of data
stb_vorbis.c(4444): warning C4244: 'return' : conversion from '__int64' to 'unsigned int', possible loss of data

**Comment by jarikomppa** [comment]
stb_vorbis I can do little about, but I think I've now covered the rest..

**Comment by petrihakkinen** [comment]
Still got these after updating to latest:
soloud_fft.cpp(109): warning C4334: '<<' : result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
soloud_fft.cpp(232): warning C4334: '<<' : result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
soloud_fft.cpp(304): warning C4334: '<<' : result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)

**Comment by r-lyeh** [comment]
`1ull <<` instead of `1 << ` should do the trick

**Comment by jarikomppa** [comment]
I don't think it should be long long =)

**Comment by jarikomppa** [comment]
Since the shift doesn't NEED to be 64 bit by any means (the result is under 16 bits), I think the warning is due to the fact the result is added to a pointer which in 64bits is.. 64 bit. I added an explicit cast to int in between, maybe that'll confuse the compiler enough not to give this warning anymore.
