### ISSUE TITLE
Deadlock when trying to lock a mutex

### ISSUE THREAD

**Issue by petrihakkinen** [jarikomppa/soloud#92]
I've had this issue two times today. Seems to be random.

XAudio2 back end is stuck here:
WaitForSingleObject(data->bufferEndEvent, INFINITE);

While the main thread is trying to lock a mutex in update3dAudio().

I'll try to find a repro case...

**Comment by petrihakkinen** [comment]
This is not XAudio2 backend related. I got the same freeze with winmm backend.

Backend thread continues to run normally but I got a mutex deadlock in set3dSourcePosition().

**Comment by petrihakkinen** [comment]
The soloud functions used in the main loop are:
set3dSourcePosition()
getWave()
getFFT()
set3dListenerParameters()
update3dAudio()

I'll try to narrow the list...

**Comment by jarikomppa** [comment]
None of those should(tm) cause the problem. Maybe something overwrites the SoLoud::Soloud::mUnlockMutexFunc pointer?

**Comment by petrihakkinen** [comment]
Checked that, function pointers are ok.

**Comment by jarikomppa** [comment]
Does that happen if you leave stuff running long enough, or does it happen instantly when you start sometimes?

**Comment by petrihakkinen** [comment]
It takes around 400-700 seconds before it freezes. So far it has never happened straight away at startup.

Ok, I added 10000 set3dSourcePosition() and update3dAudio() calls per frame and some weird stuff is starting to happen...

I get this in Visual Studio's output window after about a minute:
NTDLL: Calling thread (1968) not owner of CritSect: 0000000005D47650  Owner ThreadId: 0

Debugger breaks at LeaveCriticalSection() (called from set3dSourcePosition())

Some weird shit is going on...

**Comment by jarikomppa** [comment]
May have something to do with the 64bit build? I've tried to repro with my 32bit build with no success so far.

**Comment by petrihakkinen** [comment]
More clues: sometimes, but rarely it is possible that the audio thread gets stuck in mutex lock. Probably does not help..

Re: 64 bit build: it's possible. Shinobi does not support 32-bit builds, so it's hard to test...

**Comment by petrihakkinen** [comment]
Is this safe?

CRITICAL_SECTION *cs = (CRITICAL_SECTION*)aHandle;

**Comment by neilogd** [comment]
"CRITICAL_SECTION *cs = (CRITICAL_SECTION*)aHandle;"

That one is. void* size is the same as CRITICAL_SECTION* size. I can't see
a cast of the object type..?

**Comment by petrihakkinen** [comment]
Yep, it should be safe, just checking. For some reason cs->OwningThread = 0 when unlocking the mutex. Any ideas how that can be?

**Comment by jarikomppa** [comment]
Based on some googling that may happen if the mutex is deleted while it's locked, but that shouldn't be happening either.

Further googling says that another reason for hangs may be that unlock gets called too many times, as when critical section lock count goes to -1 it can't be acquired again(?!)

**Comment by jarikomppa** [comment]
Made a x64 build with ogg streaming and three 3d sounds flying around, updating positions a lot etc, haven't seen a crash yet :/

**Comment by petrihakkinen** [comment]
Hold on, I'm making a minimal standalone app that reproduces the issue...

**Comment by petrihakkinen** [comment]
Here's a standalone Visual Studio 2013 project that crashes after about a minute (x64 / debug configuration):
https://www.dropbox.com/s/ugkdr1wek56hqaq/soloudtest.zip

**Comment by jarikomppa** [comment]
I couldn't reproduce with my head version (not in github), went back and yes, the odd behavior happens here.

**Comment by jarikomppa** [comment]
happens in 32bit mode too.

**Comment by petrihakkinen** [comment]
I narrowed the test case further. No ogg needed and just one 3d sound remaining.
https://www.dropbox.com/s/ugkdr1wek56hqaq/soloudtest.zip

**Comment by jarikomppa** [comment]
Hm, can't apparently get it to hang, there's no missile.wav in the zip though (switched to load another wav)

**Comment by petrihakkinen** [comment]
It crashes, it just takes longer. I just tested and it took 360 seconds.

**Comment by petrihakkinen** [comment]
Here's the missile.wav I accidentally deleted:
https://www.dropbox.com/s/eg9nj21c2b4d9oa/missile.wav

**Comment by petrihakkinen** [comment]
Ok, new version of the test case. This one repros the problem in a couple of seconds:
https://www.dropbox.com/s/ugkdr1wek56hqaq/soloudtest.zip?dl=0

**Comment by jarikomppa** [comment]
Okay, with that version I can repro, and also on my head version (which has a bit different memory layout).

**Comment by petrihakkinen** [comment]
Okay found it!  Search for:

if (mLockMutexFunc) mUnlockMutexFunc(mMutex);   // !!!

**Comment by petrihakkinen** [comment]
Suggestion: you can eliminate the if(mLockMutexFunc) and if(mUnlockMutexFunc) branches (and clean up the code a bit) by setting a stub for those backends that don't need mutexes (don't they all need a mutex?)

**Comment by petrihakkinen** [comment]
The buggy functions are:
set3dListenerParameters, set3dListenerPosition, set3dListenerAt, set3dListenerUp, set3dListenerVelocity

After fixing these, the issue does not repro anymore.

**Comment by jarikomppa** [comment]
Okay, how the heck has that worked in the first place.. good catch, bad copy-paste.
