### ISSUE TITLE
Lock free command buffer

### ISSUE THREAD

**Issue by petrihakkinen** [jarikomppa/soloud#93]
This is not really an issue, but something to start a discussion.

Currently every soloud API call locks a mutex, which could be inefficient, for example, when there are a lot of moving 3d sounds. Have you considered a lock free command buffer style API, where the calls are queued in a command buffer and later executed in one shot in Soloud::updateAudio()?

**Comment by jarikomppa** [comment]
Already have some work done towards that.. =)

**Comment by neilogd** [comment]
That's good to know, I was tempted by it a while ago. Would put you ahead
of some of the commercial sound engines..

**Comment by jarikomppa** [comment]
I really doubt that. My motivation is to move stuff out of the audio thread. I trust commercial sound engines handle audio threads in more sane manner.

**Comment by jarikomppa** [comment]
I've moved (most of) the 3d ops outside audio mutex. I'll close this issue now, but having a more generic cache-and-issue mechanism might be handy.
