### ISSUE TITLE
LEFT_HANDED_3D & at-vector

### ISSUE THREAD

**Issue by petrihakkinen** [jarikomppa/soloud#94]
Currently the LEFT_HANDED_3D flag flips the at-vector, which causes sounds in front of the listener to attenuate more than sounds behind the listener (with "front" I mean the half space where the at-vector is pointing to). Instead of flipping at-vector, a more sensible behavior is to flip the side vector calculated from at and up-vectors. This is the convention used by DirectX and many engines using a left-handed coordinate system, where +Z points forward, +Y points up and +X points to the left.

I suggest the following change to lookAtLH:

		void lookatLH(vec3 at, vec3 up)
		{
			//at.neg();
			vec3 z = at;
			z.normalize();
			vec3 x = up.cross(z);
			x.normalize();
			vec3 y = z.cross(x);
			x.neg();  // flip x
			m[0] = x;
			m[1] = y;
			m[2] = z;
		}

**Comment by jarikomppa** [comment]
Done, I have no test case for this so I'll take your word for it.

**Comment by petrihakkinen** [comment]
Thanks! Tested to work perfectly.
