### ISSUE TITLE
Arithmetic error if using large 3d velocities for doppler.

### ISSUE THREAD

**Issue by neilogd** [jarikomppa/soloud#97]
Hitting an arithmetic error here: https://github.com/jarikomppa/soloud/blob/master/src/core/soloud.cpp#L644
writesamples = ((SAMPLE_GRANULARITY * FIXPOINT_FRAC_MUL) - voice->mSrcOffset) / step_fixed + 1;

step_fixed is 0. m3dDopplerFactor is set to 0.0 during the 3D update here: https://github.com/jarikomppa/soloud/blob/master/src/core/soloud_core_3d.cpp#L282
v->mDopplerValue = doppler(pos, vel, lvel, v->m3dDopplerFactor, m3dSoundSpeed);

pos = 0.0, 0.0, 0.0
vel = 0.0, 0.0, 0.0
lvel = 0.0, 0.0, -1602.810791
v->m3dDopplerFactor = 1.0
m3dSoundSpeed = 343.299988

Not sure if the doppler factor should be getting clamped to a sensible range, or if the bug is with the mixing not handling ~0 play back rates.

**Comment by jarikomppa** [comment]
Fixed by skipping sample processing if step_fixed is zero.
