### ISSUE TITLE
setRelativePlaySpeed appears to override the doppler effect.

### ISSUE THREAD

**Issue by neilogd** [jarikomppa/soloud#98]
If updating the relative play speed, this seems to completely stomp over the doppler effect, results in some undesirable pops between pitch on playback rather than operating as a modifier.

**Comment by jarikomppa** [comment]
Yeah, doppler sets the relative play speed. Do you need relative play speed on top of the doppler?

**Comment by neilogd** [comment]
Yeah I was trying to do this. I can hold back on having doppler for the moment, since adjustable relative play speed + 3D positional audio is more useful to me than having doppler on top of that.

**Comment by jarikomppa** [comment]
Ok, I'll add the separate volume and play speed sometime in the next 48
hours =)

**Comment by neilogd** [comment]
Awesome :)
